package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * AlmDetaInsumosId generated by hbm2java
 */
public class AlmDetaInsumosId  implements java.io.Serializable {


     private String codInsBase;
     private String codIns;

    public AlmDetaInsumosId() {
    }

    public AlmDetaInsumosId(String codInsBase, String codIns) {
       this.codInsBase = codInsBase;
       this.codIns = codIns;
    }
   
    public String getCodInsBase() {
        return this.codInsBase;
    }
    
    public void setCodInsBase(String codInsBase) {
        this.codInsBase = codInsBase;
    }
    public String getCodIns() {
        return this.codIns;
    }
    
    public void setCodIns(String codIns) {
        this.codIns = codIns;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlmDetaInsumosId) ) return false;
		 AlmDetaInsumosId castOther = ( AlmDetaInsumosId ) other; 
         
		 return ( (this.getCodInsBase()==castOther.getCodInsBase()) || ( this.getCodInsBase()!=null && castOther.getCodInsBase()!=null && this.getCodInsBase().equals(castOther.getCodInsBase()) ) )
 && ( (this.getCodIns()==castOther.getCodIns()) || ( this.getCodIns()!=null && castOther.getCodIns()!=null && this.getCodIns().equals(castOther.getCodIns()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodInsBase() == null ? 0 : this.getCodInsBase().hashCode() );
         result = 37 * result + ( getCodIns() == null ? 0 : this.getCodIns().hashCode() );
         return result;
   }   


}


