package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * AlmDetapedidoVta generated by hbm2java
 */
public class AlmDetapedidoVta  implements java.io.Serializable {


     private AlmDetapedidoVtaId id;
     private BigDecimal qtyPed;
     private BigDecimal qtyRem;
     private BigDecimal qtyfac;
     private BigDecimal valing;
     private BigDecimal valiva;
     private BigDecimal valdcto;
     private BigDecimal margenIva;
     private BigDecimal margendcto;
     private BigDecimal valorUnitario;
     private String estado;
     private int idReg;

    public AlmDetapedidoVta() {
    }

    public AlmDetapedidoVta(AlmDetapedidoVtaId id, BigDecimal qtyPed, BigDecimal qtyRem, BigDecimal qtyfac, BigDecimal valing, BigDecimal valiva, BigDecimal valdcto, BigDecimal margenIva, BigDecimal margendcto, BigDecimal valorUnitario, String estado, int idReg) {
       this.id = id;
       this.qtyPed = qtyPed;
       this.qtyRem = qtyRem;
       this.qtyfac = qtyfac;
       this.valing = valing;
       this.valiva = valiva;
       this.valdcto = valdcto;
       this.margenIva = margenIva;
       this.margendcto = margendcto;
       this.valorUnitario = valorUnitario;
       this.estado = estado;
       this.idReg = idReg;
    }
   
    public AlmDetapedidoVtaId getId() {
        return this.id;
    }
    
    public void setId(AlmDetapedidoVtaId id) {
        this.id = id;
    }
    public BigDecimal getQtyPed() {
        return this.qtyPed;
    }
    
    public void setQtyPed(BigDecimal qtyPed) {
        this.qtyPed = qtyPed;
    }
    public BigDecimal getQtyRem() {
        return this.qtyRem;
    }
    
    public void setQtyRem(BigDecimal qtyRem) {
        this.qtyRem = qtyRem;
    }
    public BigDecimal getQtyfac() {
        return this.qtyfac;
    }
    
    public void setQtyfac(BigDecimal qtyfac) {
        this.qtyfac = qtyfac;
    }
    public BigDecimal getValing() {
        return this.valing;
    }
    
    public void setValing(BigDecimal valing) {
        this.valing = valing;
    }
    public BigDecimal getValiva() {
        return this.valiva;
    }
    
    public void setValiva(BigDecimal valiva) {
        this.valiva = valiva;
    }
    public BigDecimal getValdcto() {
        return this.valdcto;
    }
    
    public void setValdcto(BigDecimal valdcto) {
        this.valdcto = valdcto;
    }
    public BigDecimal getMargenIva() {
        return this.margenIva;
    }
    
    public void setMargenIva(BigDecimal margenIva) {
        this.margenIva = margenIva;
    }
    public BigDecimal getMargendcto() {
        return this.margendcto;
    }
    
    public void setMargendcto(BigDecimal margendcto) {
        this.margendcto = margendcto;
    }
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getIdReg() {
        return this.idReg;
    }
    
    public void setIdReg(int idReg) {
        this.idReg = idReg;
    }




}


