package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * AlmDetaPedidoVentaRm generated by hbm2java
 */
public class AlmDetaPedidoVentaRm  implements java.io.Serializable {


     private AlmDetaPedidoVentaRmId id;
     private BigDecimal qtyRem;
     private String numFac;
     private String tipfac;
     private String codRes;
     private String estado;
     private String codTalla;
     private String tipRem;

    public AlmDetaPedidoVentaRm() {
    }

    public AlmDetaPedidoVentaRm(AlmDetaPedidoVentaRmId id, BigDecimal qtyRem, String numFac, String tipfac, String codRes, String estado, String codTalla, String tipRem) {
       this.id = id;
       this.qtyRem = qtyRem;
       this.numFac = numFac;
       this.tipfac = tipfac;
       this.codRes = codRes;
       this.estado = estado;
       this.codTalla = codTalla;
       this.tipRem = tipRem;
    }
   
    public AlmDetaPedidoVentaRmId getId() {
        return this.id;
    }
    
    public void setId(AlmDetaPedidoVentaRmId id) {
        this.id = id;
    }
    public BigDecimal getQtyRem() {
        return this.qtyRem;
    }
    
    public void setQtyRem(BigDecimal qtyRem) {
        this.qtyRem = qtyRem;
    }
    public String getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(String numFac) {
        this.numFac = numFac;
    }
    public String getTipfac() {
        return this.tipfac;
    }
    
    public void setTipfac(String tipfac) {
        this.tipfac = tipfac;
    }
    public String getCodRes() {
        return this.codRes;
    }
    
    public void setCodRes(String codRes) {
        this.codRes = codRes;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodTalla() {
        return this.codTalla;
    }
    
    public void setCodTalla(String codTalla) {
        this.codTalla = codTalla;
    }
    public String getTipRem() {
        return this.tipRem;
    }
    
    public void setTipRem(String tipRem) {
        this.tipRem = tipRem;
    }




}


