package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * AlmDetaTrasladoId generated by hbm2java
 */
public class AlmDetaTrasladoId  implements java.io.Serializable {


     private String codAlmOri;
     private String numSalOri;
     private String codIns;
     private String codtalla;

    public AlmDetaTrasladoId() {
    }

    public AlmDetaTrasladoId(String codAlmOri, String numSalOri, String codIns, String codtalla) {
       this.codAlmOri = codAlmOri;
       this.numSalOri = numSalOri;
       this.codIns = codIns;
       this.codtalla = codtalla;
    }
   
    public String getCodAlmOri() {
        return this.codAlmOri;
    }
    
    public void setCodAlmOri(String codAlmOri) {
        this.codAlmOri = codAlmOri;
    }
    public String getNumSalOri() {
        return this.numSalOri;
    }
    
    public void setNumSalOri(String numSalOri) {
        this.numSalOri = numSalOri;
    }
    public String getCodIns() {
        return this.codIns;
    }
    
    public void setCodIns(String codIns) {
        this.codIns = codIns;
    }
    public String getCodtalla() {
        return this.codtalla;
    }
    
    public void setCodtalla(String codtalla) {
        this.codtalla = codtalla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlmDetaTrasladoId) ) return false;
		 AlmDetaTrasladoId castOther = ( AlmDetaTrasladoId ) other; 
         
		 return ( (this.getCodAlmOri()==castOther.getCodAlmOri()) || ( this.getCodAlmOri()!=null && castOther.getCodAlmOri()!=null && this.getCodAlmOri().equals(castOther.getCodAlmOri()) ) )
 && ( (this.getNumSalOri()==castOther.getNumSalOri()) || ( this.getNumSalOri()!=null && castOther.getNumSalOri()!=null && this.getNumSalOri().equals(castOther.getNumSalOri()) ) )
 && ( (this.getCodIns()==castOther.getCodIns()) || ( this.getCodIns()!=null && castOther.getCodIns()!=null && this.getCodIns().equals(castOther.getCodIns()) ) )
 && ( (this.getCodtalla()==castOther.getCodtalla()) || ( this.getCodtalla()!=null && castOther.getCodtalla()!=null && this.getCodtalla().equals(castOther.getCodtalla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlmOri() == null ? 0 : this.getCodAlmOri().hashCode() );
         result = 37 * result + ( getNumSalOri() == null ? 0 : this.getNumSalOri().hashCode() );
         result = 37 * result + ( getCodIns() == null ? 0 : this.getCodIns().hashCode() );
         result = 37 * result + ( getCodtalla() == null ? 0 : this.getCodtalla().hashCode() );
         return result;
   }   


}


