package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * AlmMaeMultiProd generated by hbm2java
 */
public class AlmMaeMultiProd  implements java.io.Serializable {


     private AlmMaeMultiProdId id;
     private String nomOpc;

    public AlmMaeMultiProd() {
    }

    public AlmMaeMultiProd(AlmMaeMultiProdId id, String nomOpc) {
       this.id = id;
       this.nomOpc = nomOpc;
    }
   
    public AlmMaeMultiProdId getId() {
        return this.id;
    }
    
    public void setId(AlmMaeMultiProdId id) {
        this.id = id;
    }
    public String getNomOpc() {
        return this.nomOpc;
    }
    
    public void setNomOpc(String nomOpc) {
        this.nomOpc = nomOpc;
    }




}


