package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * AlmMaeTrasladoId generated by hbm2java
 */
public class AlmMaeTrasladoId  implements java.io.Serializable {


     private String codAlmOri;
     private String numSalOri;

    public AlmMaeTrasladoId() {
    }

    public AlmMaeTrasladoId(String codAlmOri, String numSalOri) {
       this.codAlmOri = codAlmOri;
       this.numSalOri = numSalOri;
    }
   
    public String getCodAlmOri() {
        return this.codAlmOri;
    }
    
    public void setCodAlmOri(String codAlmOri) {
        this.codAlmOri = codAlmOri;
    }
    public String getNumSalOri() {
        return this.numSalOri;
    }
    
    public void setNumSalOri(String numSalOri) {
        this.numSalOri = numSalOri;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlmMaeTrasladoId) ) return false;
		 AlmMaeTrasladoId castOther = ( AlmMaeTrasladoId ) other; 
         
		 return ( (this.getCodAlmOri()==castOther.getCodAlmOri()) || ( this.getCodAlmOri()!=null && castOther.getCodAlmOri()!=null && this.getCodAlmOri().equals(castOther.getCodAlmOri()) ) )
 && ( (this.getNumSalOri()==castOther.getNumSalOri()) || ( this.getNumSalOri()!=null && castOther.getNumSalOri()!=null && this.getNumSalOri().equals(castOther.getNumSalOri()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlmOri() == null ? 0 : this.getCodAlmOri().hashCode() );
         result = 37 * result + ( getNumSalOri() == null ? 0 : this.getNumSalOri().hashCode() );
         return result;
   }   


}


