package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * AlmMarcas generated by hbm2java
 */
public class AlmMarcas  implements java.io.Serializable {


     private String codmar;
     private String nommar;

    public AlmMarcas() {
    }

    public AlmMarcas(String codmar, String nommar) {
       this.codmar = codmar;
       this.nommar = nommar;
    }
   
    public String getCodmar() {
        return this.codmar;
    }
    
    public void setCodmar(String codmar) {
        this.codmar = codmar;
    }
    public String getNommar() {
        return this.nommar;
    }
    
    public void setNommar(String nommar) {
        this.nommar = nommar;
    }




}


