package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * AlmMaeDiseñoCb generated by hbm2java
 */
public class AlmMaeDiseñoCb  implements java.io.Serializable {


     private String coddis;
     private String nomdis;

    public AlmMaeDiseñoCb() {
    }

    public AlmMaeDiseñoCb(String coddis, String nomdis) {
       this.coddis = coddis;
       this.nomdis = nomdis;
    }
   
    public String getCoddis() {
        return this.coddis;
    }
    
    public void setCoddis(String coddis) {
        this.coddis = coddis;
    }
    public String getNomdis() {
        return this.nomdis;
    }
    
    public void setNomdis(String nomdis) {
        this.nomdis = nomdis;
    }




}


