package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * AlmMaeTraslado generated by hbm2java
 */
public class AlmMaeTraslado  implements java.io.Serializable {


     private AlmMaeTrasladoId id;
     private String codAlmDes;
     private Date fecha;
     private String estado;
     private String codUsu;
     private Date fecSys;
     private String pc;
     private String observa;
     private char tiptra;

    public AlmMaeTraslado() {
    }

	
    public AlmMaeTraslado(AlmMaeTrasladoId id, String codAlmDes, String estado, String codUsu, String pc, String observa, char tiptra) {
        this.id = id;
        this.codAlmDes = codAlmDes;
        this.estado = estado;
        this.codUsu = codUsu;
        this.pc = pc;
        this.observa = observa;
        this.tiptra = tiptra;
    }
    public AlmMaeTraslado(AlmMaeTrasladoId id, String codAlmDes, Date fecha, String estado, String codUsu, Date fecSys, String pc, String observa, char tiptra) {
       this.id = id;
       this.codAlmDes = codAlmDes;
       this.fecha = fecha;
       this.estado = estado;
       this.codUsu = codUsu;
       this.fecSys = fecSys;
       this.pc = pc;
       this.observa = observa;
       this.tiptra = tiptra;
    }
   
    public AlmMaeTrasladoId getId() {
        return this.id;
    }
    
    public void setId(AlmMaeTrasladoId id) {
        this.id = id;
    }
    public String getCodAlmDes() {
        return this.codAlmDes;
    }
    
    public void setCodAlmDes(String codAlmDes) {
        this.codAlmDes = codAlmDes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }
    public String getObserva() {
        return this.observa;
    }
    
    public void setObserva(String observa) {
        this.observa = observa;
    }
    public char getTiptra() {
        return this.tiptra;
    }
    
    public void setTiptra(char tiptra) {
        this.tiptra = tiptra;
    }




}


