package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * AlmSaldosTras generated by hbm2java
 */
public class AlmSaldosTras  implements java.io.Serializable {


     private AlmSaldosTrasId id;
     private BigDecimal valTras;
     private BigDecimal valAbo;
     private Date fecha;
     private Date fecSys;
     private String codUsu;

    public AlmSaldosTras() {
    }

    public AlmSaldosTras(AlmSaldosTrasId id, BigDecimal valTras, BigDecimal valAbo, Date fecha, Date fecSys, String codUsu) {
       this.id = id;
       this.valTras = valTras;
       this.valAbo = valAbo;
       this.fecha = fecha;
       this.fecSys = fecSys;
       this.codUsu = codUsu;
    }
   
    public AlmSaldosTrasId getId() {
        return this.id;
    }
    
    public void setId(AlmSaldosTrasId id) {
        this.id = id;
    }
    public BigDecimal getValTras() {
        return this.valTras;
    }
    
    public void setValTras(BigDecimal valTras) {
        this.valTras = valTras;
    }
    public BigDecimal getValAbo() {
        return this.valAbo;
    }
    
    public void setValAbo(BigDecimal valAbo) {
        this.valAbo = valAbo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }




}


