package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * CfgConfigReportsTerId generated by hbm2java
 */
public class CfgConfigReportsTerId  implements java.io.Serializable {


     private String idProcess;
     private String codalm;
     private String codter;

    public CfgConfigReportsTerId() {
    }

    public CfgConfigReportsTerId(String idProcess, String codalm, String codter) {
       this.idProcess = idProcess;
       this.codalm = codalm;
       this.codter = codter;
    }
   
    public String getIdProcess() {
        return this.idProcess;
    }
    
    public void setIdProcess(String idProcess) {
        this.idProcess = idProcess;
    }
    public String getCodalm() {
        return this.codalm;
    }
    
    public void setCodalm(String codalm) {
        this.codalm = codalm;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgConfigReportsTerId) ) return false;
		 CfgConfigReportsTerId castOther = ( CfgConfigReportsTerId ) other; 
         
		 return ( (this.getIdProcess()==castOther.getIdProcess()) || ( this.getIdProcess()!=null && castOther.getIdProcess()!=null && this.getIdProcess().equals(castOther.getIdProcess()) ) )
 && ( (this.getCodalm()==castOther.getCodalm()) || ( this.getCodalm()!=null && castOther.getCodalm()!=null && this.getCodalm().equals(castOther.getCodalm()) ) )
 && ( (this.getCodter()==castOther.getCodter()) || ( this.getCodter()!=null && castOther.getCodter()!=null && this.getCodter().equals(castOther.getCodter()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProcess() == null ? 0 : this.getIdProcess().hashCode() );
         result = 37 * result + ( getCodalm() == null ? 0 : this.getCodalm().hashCode() );
         result = 37 * result + ( getCodter() == null ? 0 : this.getCodter().hashCode() );
         return result;
   }   


}


