package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * CfgDetaPerfil generated by hbm2java
 */
public class CfgDetaPerfil  implements java.io.Serializable {


     private CfgDetaPerfilId id;

    public CfgDetaPerfil() {
    }

    public CfgDetaPerfil(CfgDetaPerfilId id) {
       this.id = id;
    }
   
    public CfgDetaPerfilId getId() {
        return this.id;
    }
    
    public void setId(CfgDetaPerfilId id) {
        this.id = id;
    }




}


