package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * CfgDetaPerfilId generated by hbm2java
 */
public class CfgDetaPerfilId  implements java.io.Serializable {


     private String codper;
     private String formulario;

    public CfgDetaPerfilId() {
    }

    public CfgDetaPerfilId(String codper, String formulario) {
       this.codper = codper;
       this.formulario = formulario;
    }
   
    public String getCodper() {
        return this.codper;
    }
    
    public void setCodper(String codper) {
        this.codper = codper;
    }
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgDetaPerfilId) ) return false;
		 CfgDetaPerfilId castOther = ( CfgDetaPerfilId ) other; 
         
		 return ( (this.getCodper()==castOther.getCodper()) || ( this.getCodper()!=null && castOther.getCodper()!=null && this.getCodper().equals(castOther.getCodper()) ) )
 && ( (this.getFormulario()==castOther.getFormulario()) || ( this.getFormulario()!=null && castOther.getFormulario()!=null && this.getFormulario().equals(castOther.getFormulario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodper() == null ? 0 : this.getCodper().hashCode() );
         result = 37 * result + ( getFormulario() == null ? 0 : this.getFormulario().hashCode() );
         return result;
   }   


}


