package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * CfgPerfilxUsua generated by hbm2java
 */
public class CfgPerfilxUsua  implements java.io.Serializable {


     private CfgPerfilxUsuaId id;

    public CfgPerfilxUsua() {
    }

    public CfgPerfilxUsua(CfgPerfilxUsuaId id) {
       this.id = id;
    }
   
    public CfgPerfilxUsuaId getId() {
        return this.id;
    }
    
    public void setId(CfgPerfilxUsuaId id) {
        this.id = id;
    }




}


