package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * CfgUsuarios generated by hbm2java
 */
public class CfgUsuarios  implements java.io.Serializable {


     private String userName;
     private String nombre1;
     private String nombre2;
     private String apellido1;
     private String apellido2;
     private String cedula;
     private String cargo;
     private Boolean activo;
     private String pwd;
     private String nombreCom;
     private boolean visualizaCostos;
     private boolean notificarupd;

    public CfgUsuarios() {
    }

	
    public CfgUsuarios(String userName, String nombre1, String nombre2, String cedula, String cargo, String pwd, String nombreCom, boolean visualizaCostos, boolean notificarupd) {
        this.userName = userName;
        this.nombre1 = nombre1;
        this.nombre2 = nombre2;
        this.cedula = cedula;
        this.cargo = cargo;
        this.pwd = pwd;
        this.nombreCom = nombreCom;
        this.visualizaCostos = visualizaCostos;
        this.notificarupd = notificarupd;
    }
    public CfgUsuarios(String userName, String nombre1, String nombre2, String apellido1, String apellido2, String cedula, String cargo, Boolean activo, String pwd, String nombreCom, boolean visualizaCostos, boolean notificarupd) {
       this.userName = userName;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.cedula = cedula;
       this.cargo = cargo;
       this.activo = activo;
       this.pwd = pwd;
       this.nombreCom = nombreCom;
       this.visualizaCostos = visualizaCostos;
       this.notificarupd = notificarupd;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getNombreCom() {
        return this.nombreCom;
    }
    
    public void setNombreCom(String nombreCom) {
        this.nombreCom = nombreCom;
    }
    public boolean isVisualizaCostos() {
        return this.visualizaCostos;
    }
    
    public void setVisualizaCostos(boolean visualizaCostos) {
        this.visualizaCostos = visualizaCostos;
    }
    public boolean isNotificarupd() {
        return this.notificarupd;
    }
    
    public void setNotificarupd(boolean notificarupd) {
        this.notificarupd = notificarupd;
    }




}


