package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * CfgUsuariosxAlm generated by hbm2java
 */
public class CfgUsuariosxAlm  implements java.io.Serializable {


     private CfgUsuariosxAlmId id;

    public CfgUsuariosxAlm() {
    }

    public CfgUsuariosxAlm(CfgUsuariosxAlmId id) {
       this.id = id;
    }
   
    public CfgUsuariosxAlmId getId() {
        return this.id;
    }
    
    public void setId(CfgUsuariosxAlmId id) {
        this.id = id;
    }




}


