package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * CfgUsuariosxAlmId generated by hbm2java
 */
public class CfgUsuariosxAlmId  implements java.io.Serializable {


     private String codusu;
     private String codalm;

    public CfgUsuariosxAlmId() {
    }

    public CfgUsuariosxAlmId(String codusu, String codalm) {
       this.codusu = codusu;
       this.codalm = codalm;
    }
   
    public String getCodusu() {
        return this.codusu;
    }
    
    public void setCodusu(String codusu) {
        this.codusu = codusu;
    }
    public String getCodalm() {
        return this.codalm;
    }
    
    public void setCodalm(String codalm) {
        this.codalm = codalm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CfgUsuariosxAlmId) ) return false;
		 CfgUsuariosxAlmId castOther = ( CfgUsuariosxAlmId ) other; 
         
		 return ( (this.getCodusu()==castOther.getCodusu()) || ( this.getCodusu()!=null && castOther.getCodusu()!=null && this.getCodusu().equals(castOther.getCodusu()) ) )
 && ( (this.getCodalm()==castOther.getCodalm()) || ( this.getCodalm()!=null && castOther.getCodalm()!=null && this.getCodalm().equals(castOther.getCodalm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodusu() == null ? 0 : this.getCodusu().hashCode() );
         result = 37 * result + ( getCodalm() == null ? 0 : this.getCodalm().hashCode() );
         return result;
   }   


}


