package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CntComprobantes generated by hbm2java
 */
public class CntComprobantes  implements java.io.Serializable {


     private CntComprobantesId id;
     private Date fecDoc;
     private BigDecimal debito;
     private BigDecimal credito;
     private String detalle;
     private Date fecSys;
     private String codUsu;
     private BigDecimal base;
     private String estDoc;
     private String numfac;
     private String tipfac;

    public CntComprobantes() {
    }

	
    public CntComprobantes(CntComprobantesId id, BigDecimal debito, BigDecimal credito, String detalle, Date fecSys, String codUsu, BigDecimal base, String estDoc, String numfac, String tipfac) {
        this.id = id;
        this.debito = debito;
        this.credito = credito;
        this.detalle = detalle;
        this.fecSys = fecSys;
        this.codUsu = codUsu;
        this.base = base;
        this.estDoc = estDoc;
        this.numfac = numfac;
        this.tipfac = tipfac;
    }
    public CntComprobantes(CntComprobantesId id, Date fecDoc, BigDecimal debito, BigDecimal credito, String detalle, Date fecSys, String codUsu, BigDecimal base, String estDoc, String numfac, String tipfac) {
       this.id = id;
       this.fecDoc = fecDoc;
       this.debito = debito;
       this.credito = credito;
       this.detalle = detalle;
       this.fecSys = fecSys;
       this.codUsu = codUsu;
       this.base = base;
       this.estDoc = estDoc;
       this.numfac = numfac;
       this.tipfac = tipfac;
    }
   
    public CntComprobantesId getId() {
        return this.id;
    }
    
    public void setId(CntComprobantesId id) {
        this.id = id;
    }
    public Date getFecDoc() {
        return this.fecDoc;
    }
    
    public void setFecDoc(Date fecDoc) {
        this.fecDoc = fecDoc;
    }
    public BigDecimal getDebito() {
        return this.debito;
    }
    
    public void setDebito(BigDecimal debito) {
        this.debito = debito;
    }
    public BigDecimal getCredito() {
        return this.credito;
    }
    
    public void setCredito(BigDecimal credito) {
        this.credito = credito;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public String getEstDoc() {
        return this.estDoc;
    }
    
    public void setEstDoc(String estDoc) {
        this.estDoc = estDoc;
    }
    public String getNumfac() {
        return this.numfac;
    }
    
    public void setNumfac(String numfac) {
        this.numfac = numfac;
    }
    public String getTipfac() {
        return this.tipfac;
    }
    
    public void setTipfac(String tipfac) {
        this.tipfac = tipfac;
    }




}


