package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * CntPeriodos generated by hbm2java
 */
public class CntPeriodos  implements java.io.Serializable {


     private CntPeriodosId id;
     private String estado;

    public CntPeriodos() {
    }

    public CntPeriodos(CntPeriodosId id, String estado) {
       this.id = id;
       this.estado = estado;
    }
   
    public CntPeriodosId getId() {
        return this.id;
    }
    
    public void setId(CntPeriodosId id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


