package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CxPActComercial generated by hbm2java
 */
public class CxPActComercial  implements java.io.Serializable {


     private String codAct;
     private String nomAct;
     private BigDecimal margenAct;
     private BigDecimal baseAct;
     private boolean modificado;
     private String codActSis;

    public CxPActComercial() {
    }

    public CxPActComercial(String codAct, String nomAct, BigDecimal margenAct, BigDecimal baseAct, boolean modificado, String codActSis) {
       this.codAct = codAct;
       this.nomAct = nomAct;
       this.margenAct = margenAct;
       this.baseAct = baseAct;
       this.modificado = modificado;
       this.codActSis = codActSis;
    }
   
    public String getCodAct() {
        return this.codAct;
    }
    
    public void setCodAct(String codAct) {
        this.codAct = codAct;
    }
    public String getNomAct() {
        return this.nomAct;
    }
    
    public void setNomAct(String nomAct) {
        this.nomAct = nomAct;
    }
    public BigDecimal getMargenAct() {
        return this.margenAct;
    }
    
    public void setMargenAct(BigDecimal margenAct) {
        this.margenAct = margenAct;
    }
    public BigDecimal getBaseAct() {
        return this.baseAct;
    }
    
    public void setBaseAct(BigDecimal baseAct) {
        this.baseAct = baseAct;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public String getCodActSis() {
        return this.codActSis;
    }
    
    public void setCodActSis(String codActSis) {
        this.codActSis = codActSis;
    }




}


