package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * CxPConceptosNotas generated by hbm2java
 */
public class CxPConceptosNotas  implements java.io.Serializable {


     private String codCon;
     private String nomCon;
     private String codCue;
     private String tipCon;
     private String codCueIva;
     private boolean modificado;

    public CxPConceptosNotas() {
    }

    public CxPConceptosNotas(String codCon, String nomCon, String codCue, String tipCon, String codCueIva, boolean modificado) {
       this.codCon = codCon;
       this.nomCon = nomCon;
       this.codCue = codCue;
       this.tipCon = tipCon;
       this.codCueIva = codCueIva;
       this.modificado = modificado;
    }
   
    public String getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(String codCon) {
        this.codCon = codCon;
    }
    public String getNomCon() {
        return this.nomCon;
    }
    
    public void setNomCon(String nomCon) {
        this.nomCon = nomCon;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public String getTipCon() {
        return this.tipCon;
    }
    
    public void setTipCon(String tipCon) {
        this.tipCon = tipCon;
    }
    public String getCodCueIva() {
        return this.codCueIva;
    }
    
    public void setCodCueIva(String codCueIva) {
        this.codCueIva = codCueIva;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }




}


