package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CxPDetaCausa generated by hbm2java
 */
public class CxPDetaCausa  implements java.io.Serializable {


     private CxPDetaCausaId id;
     private BigDecimal debito;
     private BigDecimal credito;
     private BigDecimal base;
     private BigDecimal valCau;
     private String estado;
     private String detalle;

    public CxPDetaCausa() {
    }

    public CxPDetaCausa(CxPDetaCausaId id, BigDecimal debito, BigDecimal credito, BigDecimal base, BigDecimal valCau, String estado, String detalle) {
       this.id = id;
       this.debito = debito;
       this.credito = credito;
       this.base = base;
       this.valCau = valCau;
       this.estado = estado;
       this.detalle = detalle;
    }
   
    public CxPDetaCausaId getId() {
        return this.id;
    }
    
    public void setId(CxPDetaCausaId id) {
        this.id = id;
    }
    public BigDecimal getDebito() {
        return this.debito;
    }
    
    public void setDebito(BigDecimal debito) {
        this.debito = debito;
    }
    public BigDecimal getCredito() {
        return this.credito;
    }
    
    public void setCredito(BigDecimal credito) {
        this.credito = credito;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public BigDecimal getValCau() {
        return this.valCau;
    }
    
    public void setValCau(BigDecimal valCau) {
        this.valCau = valCau;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


