package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * CxPDetaCausaId generated by hbm2java
 */
public class CxPDetaCausaId  implements java.io.Serializable {


     private String codAlm;
     private String numCau;
     private String tipCau;
     private String codCon;
     private String codCue;
     private String codter;
     private String codCos;
     private String idregDe;

    public CxPDetaCausaId() {
    }

    public CxPDetaCausaId(String codAlm, String numCau, String tipCau, String codCon, String codCue, String codter, String codCos, String idregDe) {
       this.codAlm = codAlm;
       this.numCau = numCau;
       this.tipCau = tipCau;
       this.codCon = codCon;
       this.codCue = codCue;
       this.codter = codter;
       this.codCos = codCos;
       this.idregDe = idregDe;
    }
   
    public String getCodAlm() {
        return this.codAlm;
    }
    
    public void setCodAlm(String codAlm) {
        this.codAlm = codAlm;
    }
    public String getNumCau() {
        return this.numCau;
    }
    
    public void setNumCau(String numCau) {
        this.numCau = numCau;
    }
    public String getTipCau() {
        return this.tipCau;
    }
    
    public void setTipCau(String tipCau) {
        this.tipCau = tipCau;
    }
    public String getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(String codCon) {
        this.codCon = codCon;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }
    public String getCodCos() {
        return this.codCos;
    }
    
    public void setCodCos(String codCos) {
        this.codCos = codCos;
    }
    public String getIdregDe() {
        return this.idregDe;
    }
    
    public void setIdregDe(String idregDe) {
        this.idregDe = idregDe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CxPDetaCausaId) ) return false;
		 CxPDetaCausaId castOther = ( CxPDetaCausaId ) other; 
         
		 return ( (this.getCodAlm()==castOther.getCodAlm()) || ( this.getCodAlm()!=null && castOther.getCodAlm()!=null && this.getCodAlm().equals(castOther.getCodAlm()) ) )
 && ( (this.getNumCau()==castOther.getNumCau()) || ( this.getNumCau()!=null && castOther.getNumCau()!=null && this.getNumCau().equals(castOther.getNumCau()) ) )
 && ( (this.getTipCau()==castOther.getTipCau()) || ( this.getTipCau()!=null && castOther.getTipCau()!=null && this.getTipCau().equals(castOther.getTipCau()) ) )
 && ( (this.getCodCon()==castOther.getCodCon()) || ( this.getCodCon()!=null && castOther.getCodCon()!=null && this.getCodCon().equals(castOther.getCodCon()) ) )
 && ( (this.getCodCue()==castOther.getCodCue()) || ( this.getCodCue()!=null && castOther.getCodCue()!=null && this.getCodCue().equals(castOther.getCodCue()) ) )
 && ( (this.getCodter()==castOther.getCodter()) || ( this.getCodter()!=null && castOther.getCodter()!=null && this.getCodter().equals(castOther.getCodter()) ) )
 && ( (this.getCodCos()==castOther.getCodCos()) || ( this.getCodCos()!=null && castOther.getCodCos()!=null && this.getCodCos().equals(castOther.getCodCos()) ) )
 && ( (this.getIdregDe()==castOther.getIdregDe()) || ( this.getIdregDe()!=null && castOther.getIdregDe()!=null && this.getIdregDe().equals(castOther.getIdregDe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlm() == null ? 0 : this.getCodAlm().hashCode() );
         result = 37 * result + ( getNumCau() == null ? 0 : this.getNumCau().hashCode() );
         result = 37 * result + ( getTipCau() == null ? 0 : this.getTipCau().hashCode() );
         result = 37 * result + ( getCodCon() == null ? 0 : this.getCodCon().hashCode() );
         result = 37 * result + ( getCodCue() == null ? 0 : this.getCodCue().hashCode() );
         result = 37 * result + ( getCodter() == null ? 0 : this.getCodter().hashCode() );
         result = 37 * result + ( getCodCos() == null ? 0 : this.getCodCos().hashCode() );
         result = 37 * result + ( getIdregDe() == null ? 0 : this.getIdregDe().hashCode() );
         return result;
   }   


}


