package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CxPDetaCausa generated by hbm2java
 */
public class CxPDetaCausa  implements java.io.Serializable {


     private CxPDetaCausaId id;
     private BigDecimal debito;
     private BigDecimal credito;
     private BigDecimal base;
     private String codCos;
     private BigDecimal valCau;
     private String estado;
     private String idregDe;

    public CxPDetaCausa() {
    }

    public CxPDetaCausa(CxPDetaCausaId id, BigDecimal debito, BigDecimal credito, BigDecimal base, String codCos, BigDecimal valCau, String estado, String idregDe) {
       this.id = id;
       this.debito = debito;
       this.credito = credito;
       this.base = base;
       this.codCos = codCos;
       this.valCau = valCau;
       this.estado = estado;
       this.idregDe = idregDe;
    }
   
    public CxPDetaCausaId getId() {
        return this.id;
    }
    
    public void setId(CxPDetaCausaId id) {
        this.id = id;
    }
    public BigDecimal getDebito() {
        return this.debito;
    }
    
    public void setDebito(BigDecimal debito) {
        this.debito = debito;
    }
    public BigDecimal getCredito() {
        return this.credito;
    }
    
    public void setCredito(BigDecimal credito) {
        this.credito = credito;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public String getCodCos() {
        return this.codCos;
    }
    
    public void setCodCos(String codCos) {
        this.codCos = codCos;
    }
    public BigDecimal getValCau() {
        return this.valCau;
    }
    
    public void setValCau(BigDecimal valCau) {
        this.valCau = valCau;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getIdregDe() {
        return this.idregDe;
    }
    
    public void setIdregDe(String idregDe) {
        this.idregDe = idregDe;
    }




}


