package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CxPFacturas generated by hbm2java
 */
public class CxPFacturas  implements java.io.Serializable {


     private CxPFacturasId id;
     private String codter;
     private Date fecfac;
     private Date fecven;
     private BigDecimal valFac;
     private BigDecimal valDes;
     private BigDecimal valRet;
     private BigDecimal valIva;
     private BigDecimal valNeto;
     private BigDecimal valAbo;
     private Date fecSys;
     private String codusu;
     private String numRad;
     private String codcueCxP;
     private BigDecimal valfletes;
     private String codmon;
     private BigDecimal valotr;
     private BigDecimal valant;
     private BigDecimal valIco;
     private String codalm;
     private String codres;
     private String numfac;
     private String tipfac;

    public CxPFacturas() {
    }

    public CxPFacturas(CxPFacturasId id, String codter, Date fecfac, Date fecven, BigDecimal valFac, BigDecimal valDes, BigDecimal valRet, BigDecimal valIva, BigDecimal valNeto, BigDecimal valAbo, Date fecSys, String codusu, String numRad, String codcueCxP, BigDecimal valfletes, String codmon, BigDecimal valotr, BigDecimal valant, BigDecimal valIco, String codalm, String codres, String numfac, String tipfac) {
       this.id = id;
       this.codter = codter;
       this.fecfac = fecfac;
       this.fecven = fecven;
       this.valFac = valFac;
       this.valDes = valDes;
       this.valRet = valRet;
       this.valIva = valIva;
       this.valNeto = valNeto;
       this.valAbo = valAbo;
       this.fecSys = fecSys;
       this.codusu = codusu;
       this.numRad = numRad;
       this.codcueCxP = codcueCxP;
       this.valfletes = valfletes;
       this.codmon = codmon;
       this.valotr = valotr;
       this.valant = valant;
       this.valIco = valIco;
       this.codalm = codalm;
       this.codres = codres;
       this.numfac = numfac;
       this.tipfac = tipfac;
    }
   
    public CxPFacturasId getId() {
        return this.id;
    }
    
    public void setId(CxPFacturasId id) {
        this.id = id;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }
    public Date getFecfac() {
        return this.fecfac;
    }
    
    public void setFecfac(Date fecfac) {
        this.fecfac = fecfac;
    }
    public Date getFecven() {
        return this.fecven;
    }
    
    public void setFecven(Date fecven) {
        this.fecven = fecven;
    }
    public BigDecimal getValFac() {
        return this.valFac;
    }
    
    public void setValFac(BigDecimal valFac) {
        this.valFac = valFac;
    }
    public BigDecimal getValDes() {
        return this.valDes;
    }
    
    public void setValDes(BigDecimal valDes) {
        this.valDes = valDes;
    }
    public BigDecimal getValRet() {
        return this.valRet;
    }
    
    public void setValRet(BigDecimal valRet) {
        this.valRet = valRet;
    }
    public BigDecimal getValIva() {
        return this.valIva;
    }
    
    public void setValIva(BigDecimal valIva) {
        this.valIva = valIva;
    }
    public BigDecimal getValNeto() {
        return this.valNeto;
    }
    
    public void setValNeto(BigDecimal valNeto) {
        this.valNeto = valNeto;
    }
    public BigDecimal getValAbo() {
        return this.valAbo;
    }
    
    public void setValAbo(BigDecimal valAbo) {
        this.valAbo = valAbo;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodusu() {
        return this.codusu;
    }
    
    public void setCodusu(String codusu) {
        this.codusu = codusu;
    }
    public String getNumRad() {
        return this.numRad;
    }
    
    public void setNumRad(String numRad) {
        this.numRad = numRad;
    }
    public String getCodcueCxP() {
        return this.codcueCxP;
    }
    
    public void setCodcueCxP(String codcueCxP) {
        this.codcueCxP = codcueCxP;
    }
    public BigDecimal getValfletes() {
        return this.valfletes;
    }
    
    public void setValfletes(BigDecimal valfletes) {
        this.valfletes = valfletes;
    }
    public String getCodmon() {
        return this.codmon;
    }
    
    public void setCodmon(String codmon) {
        this.codmon = codmon;
    }
    public BigDecimal getValotr() {
        return this.valotr;
    }
    
    public void setValotr(BigDecimal valotr) {
        this.valotr = valotr;
    }
    public BigDecimal getValant() {
        return this.valant;
    }
    
    public void setValant(BigDecimal valant) {
        this.valant = valant;
    }
    public BigDecimal getValIco() {
        return this.valIco;
    }
    
    public void setValIco(BigDecimal valIco) {
        this.valIco = valIco;
    }
    public String getCodalm() {
        return this.codalm;
    }
    
    public void setCodalm(String codalm) {
        this.codalm = codalm;
    }
    public String getCodres() {
        return this.codres;
    }
    
    public void setCodres(String codres) {
        this.codres = codres;
    }
    public String getNumfac() {
        return this.numfac;
    }
    
    public void setNumfac(String numfac) {
        this.numfac = numfac;
    }
    public String getTipfac() {
        return this.tipfac;
    }
    
    public void setTipfac(String tipfac) {
        this.tipfac = tipfac;
    }




}


