package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CxPMaeCausa generated by hbm2java
 */
public class CxPMaeCausa  implements java.io.Serializable {


     private CxPMaeCausaId id;
     private String codter;
     private String numFac;
     private Date fecCau;
     private BigDecimal valCau;
     private Date fecSys;
     private String codUsu;
     private String pc;
     private String estado;
     private String codcueCred;

    public CxPMaeCausa() {
    }

	
    public CxPMaeCausa(CxPMaeCausaId id, String codter, String numFac, BigDecimal valCau, String codUsu, String pc, String estado, String codcueCred) {
        this.id = id;
        this.codter = codter;
        this.numFac = numFac;
        this.valCau = valCau;
        this.codUsu = codUsu;
        this.pc = pc;
        this.estado = estado;
        this.codcueCred = codcueCred;
    }
    public CxPMaeCausa(CxPMaeCausaId id, String codter, String numFac, Date fecCau, BigDecimal valCau, Date fecSys, String codUsu, String pc, String estado, String codcueCred) {
       this.id = id;
       this.codter = codter;
       this.numFac = numFac;
       this.fecCau = fecCau;
       this.valCau = valCau;
       this.fecSys = fecSys;
       this.codUsu = codUsu;
       this.pc = pc;
       this.estado = estado;
       this.codcueCred = codcueCred;
    }
   
    public CxPMaeCausaId getId() {
        return this.id;
    }
    
    public void setId(CxPMaeCausaId id) {
        this.id = id;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }
    public String getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(String numFac) {
        this.numFac = numFac;
    }
    public Date getFecCau() {
        return this.fecCau;
    }
    
    public void setFecCau(Date fecCau) {
        this.fecCau = fecCau;
    }
    public BigDecimal getValCau() {
        return this.valCau;
    }
    
    public void setValCau(BigDecimal valCau) {
        this.valCau = valCau;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodcueCred() {
        return this.codcueCred;
    }
    
    public void setCodcueCred(String codcueCred) {
        this.codcueCred = codcueCred;
    }




}


