package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CxPRetIcaxFac generated by hbm2java
 */
public class CxPRetIcaxFac  implements java.io.Serializable {


     private CxPRetIcaxFacId id;
     private BigDecimal base;
     private BigDecimal valRet;
     private BigDecimal margen;

    public CxPRetIcaxFac() {
    }

    public CxPRetIcaxFac(CxPRetIcaxFacId id, BigDecimal base, BigDecimal valRet, BigDecimal margen) {
       this.id = id;
       this.base = base;
       this.valRet = valRet;
       this.margen = margen;
    }
   
    public CxPRetIcaxFacId getId() {
        return this.id;
    }
    
    public void setId(CxPRetIcaxFacId id) {
        this.id = id;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public BigDecimal getValRet() {
        return this.valRet;
    }
    
    public void setValRet(BigDecimal valRet) {
        this.valRet = valRet;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }




}


