package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * CxPRetsXProv generated by hbm2java
 */
public class CxPRetsXProv  implements java.io.Serializable {


     private CxPRetsXProvId id;

    public CxPRetsXProv() {
    }

    public CxPRetsXProv(CxPRetsXProvId id) {
       this.id = id;
    }
   
    public CxPRetsXProvId getId() {
        return this.id;
    }
    
    public void setId(CxPRetsXProvId id) {
        this.id = id;
    }




}


