package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * GenConsecMId generated by hbm2java
 */
public class GenConsecMId  implements java.io.Serializable {


     private String codalm;
     private String codcon;
     private int año;
     private int mes;

    public GenConsecMId() {
    }

    public GenConsecMId(String codalm, String codcon, int año, int mes) {
       this.codalm = codalm;
       this.codcon = codcon;
       this.año = año;
       this.mes = mes;
    }
   
    public String getCodalm() {
        return this.codalm;
    }
    
    public void setCodalm(String codalm) {
        this.codalm = codalm;
    }
    public String getCodcon() {
        return this.codcon;
    }
    
    public void setCodcon(String codcon) {
        this.codcon = codcon;
    }
    public int getAño() {
        return this.año;
    }
    
    public void setAño(int año) {
        this.año = año;
    }
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenConsecMId) ) return false;
		 GenConsecMId castOther = ( GenConsecMId ) other; 
         
		 return ( (this.getCodalm()==castOther.getCodalm()) || ( this.getCodalm()!=null && castOther.getCodalm()!=null && this.getCodalm().equals(castOther.getCodalm()) ) )
 && ( (this.getCodcon()==castOther.getCodcon()) || ( this.getCodcon()!=null && castOther.getCodcon()!=null && this.getCodcon().equals(castOther.getCodcon()) ) )
 && (this.getAño()==castOther.getAño())
 && (this.getMes()==castOther.getMes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodalm() == null ? 0 : this.getCodalm().hashCode() );
         result = 37 * result + ( getCodcon() == null ? 0 : this.getCodcon().hashCode() );
         result = 37 * result + this.getAño();
         result = 37 * result + this.getMes();
         return result;
   }   


}


