package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * GenDepartamentos generated by hbm2java
 */
public class GenDepartamentos  implements java.io.Serializable {


     private String codDpto;
     private String nomDpto;

    public GenDepartamentos() {
    }

    public GenDepartamentos(String codDpto, String nomDpto) {
       this.codDpto = codDpto;
       this.nomDpto = nomDpto;
    }
   
    public String getCodDpto() {
        return this.codDpto;
    }
    
    public void setCodDpto(String codDpto) {
        this.codDpto = codDpto;
    }
    public String getNomDpto() {
        return this.nomDpto;
    }
    
    public void setNomDpto(String nomDpto) {
        this.nomDpto = nomDpto;
    }




}


