package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * GenFavoritos generated by hbm2java
 */
public class GenFavoritos  implements java.io.Serializable {


     private GenFavoritosId id;

    public GenFavoritos() {
    }

    public GenFavoritos(GenFavoritosId id) {
       this.id = id;
    }
   
    public GenFavoritosId getId() {
        return this.id;
    }
    
    public void setId(GenFavoritosId id) {
        this.id = id;
    }




}


