package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * GenHomologacion generated by hbm2java
 */
public class GenHomologacion  implements java.io.Serializable {


     private String tableName;
     private String fieldKey;
     private String criterio;
     private boolean retro;

    public GenHomologacion() {
    }

    public GenHomologacion(String tableName, String fieldKey, String criterio, boolean retro) {
       this.tableName = tableName;
       this.fieldKey = fieldKey;
       this.criterio = criterio;
       this.retro = retro;
    }
   
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getFieldKey() {
        return this.fieldKey;
    }
    
    public void setFieldKey(String fieldKey) {
        this.fieldKey = fieldKey;
    }
    public String getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(String criterio) {
        this.criterio = criterio;
    }
    public boolean isRetro() {
        return this.retro;
    }
    
    public void setRetro(boolean retro) {
        this.retro = retro;
    }




}


