package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * GenMails generated by hbm2java
 */
public class GenMails  implements java.io.Serializable {


     private String email;
     private String owner;

    public GenMails() {
    }

    public GenMails(String email, String owner) {
       this.email = email;
       this.owner = owner;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }




}


