package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * GenMenu generated by hbm2java
 */
public class GenMenu  implements java.io.Serializable {


     private String formulario;
     private String modulo;
     private String descripcion;
     private String grupo;
     private String dll;
     private int ordenItem;
     private char ordenGrupo;
     private int idreg;

    public GenMenu() {
    }

    public GenMenu(String formulario, String modulo, String descripcion, String grupo, String dll, int ordenItem, char ordenGrupo, int idreg) {
       this.formulario = formulario;
       this.modulo = modulo;
       this.descripcion = descripcion;
       this.grupo = grupo;
       this.dll = dll;
       this.ordenItem = ordenItem;
       this.ordenGrupo = ordenGrupo;
       this.idreg = idreg;
    }
   
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getDll() {
        return this.dll;
    }
    
    public void setDll(String dll) {
        this.dll = dll;
    }
    public int getOrdenItem() {
        return this.ordenItem;
    }
    
    public void setOrdenItem(int ordenItem) {
        this.ordenItem = ordenItem;
    }
    public char getOrdenGrupo() {
        return this.ordenGrupo;
    }
    
    public void setOrdenGrupo(char ordenGrupo) {
        this.ordenGrupo = ordenGrupo;
    }
    public int getIdreg() {
        return this.idreg;
    }
    
    public void setIdreg(int idreg) {
        this.idreg = idreg;
    }




}


