package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * GenNotificaEventos generated by hbm2java
 */
public class GenNotificaEventos  implements java.io.Serializable {


     private GenNotificaEventosId id;

    public GenNotificaEventos() {
    }

    public GenNotificaEventos(GenNotificaEventosId id) {
       this.id = id;
    }
   
    public GenNotificaEventosId getId() {
        return this.id;
    }
    
    public void setId(GenNotificaEventosId id) {
        this.id = id;
    }




}


