package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * GenNotificaIds generated by hbm2java
 */
public class GenNotificaIds  implements java.io.Serializable {


     private String idProcess;
     private String descrip;

    public GenNotificaIds() {
    }

    public GenNotificaIds(String idProcess, String descrip) {
       this.idProcess = idProcess;
       this.descrip = descrip;
    }
   
    public String getIdProcess() {
        return this.idProcess;
    }
    
    public void setIdProcess(String idProcess) {
        this.idProcess = idProcess;
    }
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }




}


