package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * MlClase generated by hbm2java
 */
public class MlClase  implements java.io.Serializable {


     private String codClase;
     private String nomClase;

    public MlClase() {
    }

    public MlClase(String codClase, String nomClase) {
       this.codClase = codClase;
       this.nomClase = nomClase;
    }
   
    public String getCodClase() {
        return this.codClase;
    }
    
    public void setCodClase(String codClase) {
        this.codClase = codClase;
    }
    public String getNomClase() {
        return this.nomClase;
    }
    
    public void setNomClase(String nomClase) {
        this.nomClase = nomClase;
    }




}


