package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * MlProducto generated by hbm2java
 */
public class MlProducto  implements java.io.Serializable {


     private String codProd;
     private String nomProd;

    public MlProducto() {
    }

    public MlProducto(String codProd, String nomProd) {
       this.codProd = codProd;
       this.nomProd = nomProd;
    }
   
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public String getNomProd() {
        return this.nomProd;
    }
    
    public void setNomProd(String nomProd) {
        this.nomProd = nomProd;
    }




}


