package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * MlTerpel generated by hbm2java
 */
public class MlTerpel  implements java.io.Serializable {


     private String codTerp;
     private String nomTerp;

    public MlTerpel() {
    }

    public MlTerpel(String codTerp, String nomTerp) {
       this.codTerp = codTerp;
       this.nomTerp = nomTerp;
    }
   
    public String getCodTerp() {
        return this.codTerp;
    }
    
    public void setCodTerp(String codTerp) {
        this.codTerp = codTerp;
    }
    public String getNomTerp() {
        return this.nomTerp;
    }
    
    public void setNomTerp(String nomTerp) {
        this.nomTerp = nomTerp;
    }




}


