package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * MlZonas generated by hbm2java
 */
public class MlZonas  implements java.io.Serializable {


     private String codZona;
     private String nomZona;
     private String codCaja;

    public MlZonas() {
    }

    public MlZonas(String codZona, String nomZona, String codCaja) {
       this.codZona = codZona;
       this.nomZona = nomZona;
       this.codCaja = codCaja;
    }
   
    public String getCodZona() {
        return this.codZona;
    }
    
    public void setCodZona(String codZona) {
        this.codZona = codZona;
    }
    public String getNomZona() {
        return this.nomZona;
    }
    
    public void setNomZona(String nomZona) {
        this.nomZona = nomZona;
    }
    public String getCodCaja() {
        return this.codCaja;
    }
    
    public void setCodCaja(String codCaja) {
        this.codCaja = codCaja;
    }




}


