package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * NomArp generated by hbm2java
 */
public class NomArp  implements java.io.Serializable {


     private String codArp;
     private String codTer;

    public NomArp() {
    }

    public NomArp(String codArp, String codTer) {
       this.codArp = codArp;
       this.codTer = codTer;
    }
   
    public String getCodArp() {
        return this.codArp;
    }
    
    public void setCodArp(String codArp) {
        this.codArp = codArp;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }




}


