package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * NomCtasParafiscales generated by hbm2java
 */
public class NomCtasParafiscales  implements java.io.Serializable {


     private String codSec;
     private String ctaDebSalud;
     private String ctaDebPension;
     private String ctaDebArp;
     private String ctaDebCaja;
     private String ctaDebIcbf;
     private String ctaDebSena;
     private String ctaCreSalud;
     private String ctaCrePension;
     private String ctaCreArp;
     private String ctaCreCaja;
     private String ctaCreIcbf;
     private String ctaCreSena;

    public NomCtasParafiscales() {
    }

    public NomCtasParafiscales(String codSec, String ctaDebSalud, String ctaDebPension, String ctaDebArp, String ctaDebCaja, String ctaDebIcbf, String ctaDebSena, String ctaCreSalud, String ctaCrePension, String ctaCreArp, String ctaCreCaja, String ctaCreIcbf, String ctaCreSena) {
       this.codSec = codSec;
       this.ctaDebSalud = ctaDebSalud;
       this.ctaDebPension = ctaDebPension;
       this.ctaDebArp = ctaDebArp;
       this.ctaDebCaja = ctaDebCaja;
       this.ctaDebIcbf = ctaDebIcbf;
       this.ctaDebSena = ctaDebSena;
       this.ctaCreSalud = ctaCreSalud;
       this.ctaCrePension = ctaCrePension;
       this.ctaCreArp = ctaCreArp;
       this.ctaCreCaja = ctaCreCaja;
       this.ctaCreIcbf = ctaCreIcbf;
       this.ctaCreSena = ctaCreSena;
    }
   
    public String getCodSec() {
        return this.codSec;
    }
    
    public void setCodSec(String codSec) {
        this.codSec = codSec;
    }
    public String getCtaDebSalud() {
        return this.ctaDebSalud;
    }
    
    public void setCtaDebSalud(String ctaDebSalud) {
        this.ctaDebSalud = ctaDebSalud;
    }
    public String getCtaDebPension() {
        return this.ctaDebPension;
    }
    
    public void setCtaDebPension(String ctaDebPension) {
        this.ctaDebPension = ctaDebPension;
    }
    public String getCtaDebArp() {
        return this.ctaDebArp;
    }
    
    public void setCtaDebArp(String ctaDebArp) {
        this.ctaDebArp = ctaDebArp;
    }
    public String getCtaDebCaja() {
        return this.ctaDebCaja;
    }
    
    public void setCtaDebCaja(String ctaDebCaja) {
        this.ctaDebCaja = ctaDebCaja;
    }
    public String getCtaDebIcbf() {
        return this.ctaDebIcbf;
    }
    
    public void setCtaDebIcbf(String ctaDebIcbf) {
        this.ctaDebIcbf = ctaDebIcbf;
    }
    public String getCtaDebSena() {
        return this.ctaDebSena;
    }
    
    public void setCtaDebSena(String ctaDebSena) {
        this.ctaDebSena = ctaDebSena;
    }
    public String getCtaCreSalud() {
        return this.ctaCreSalud;
    }
    
    public void setCtaCreSalud(String ctaCreSalud) {
        this.ctaCreSalud = ctaCreSalud;
    }
    public String getCtaCrePension() {
        return this.ctaCrePension;
    }
    
    public void setCtaCrePension(String ctaCrePension) {
        this.ctaCrePension = ctaCrePension;
    }
    public String getCtaCreArp() {
        return this.ctaCreArp;
    }
    
    public void setCtaCreArp(String ctaCreArp) {
        this.ctaCreArp = ctaCreArp;
    }
    public String getCtaCreCaja() {
        return this.ctaCreCaja;
    }
    
    public void setCtaCreCaja(String ctaCreCaja) {
        this.ctaCreCaja = ctaCreCaja;
    }
    public String getCtaCreIcbf() {
        return this.ctaCreIcbf;
    }
    
    public void setCtaCreIcbf(String ctaCreIcbf) {
        this.ctaCreIcbf = ctaCreIcbf;
    }
    public String getCtaCreSena() {
        return this.ctaCreSena;
    }
    
    public void setCtaCreSena(String ctaCreSena) {
        this.ctaCreSena = ctaCreSena;
    }




}


