package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * NomCargos generated by hbm2java
 */
public class NomCargos  implements java.io.Serializable {


     private String codCargo;
     private String nomCargo;

    public NomCargos() {
    }

    public NomCargos(String codCargo, String nomCargo) {
       this.codCargo = codCargo;
       this.nomCargo = nomCargo;
    }
   
    public String getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(String codCargo) {
        this.codCargo = codCargo;
    }
    public String getNomCargo() {
        return this.nomCargo;
    }
    
    public void setNomCargo(String nomCargo) {
        this.nomCargo = nomCargo;
    }




}


