package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * NomCajas generated by hbm2java
 */
public class NomCajas  implements java.io.Serializable {


     private String codCaja;
     private String codTer;

    public NomCajas() {
    }

    public NomCajas(String codCaja, String codTer) {
       this.codCaja = codCaja;
       this.codTer = codTer;
    }
   
    public String getCodCaja() {
        return this.codCaja;
    }
    
    public void setCodCaja(String codCaja) {
        this.codCaja = codCaja;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }




}


