package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * NomDetaPrestamo generated by hbm2java
 */
public class NomDetaPrestamo  implements java.io.Serializable {


     private NomDetaPrestamoId id;
     private String numCuo;
     private BigDecimal valCuo;
     private BigDecimal valAbo;

    public NomDetaPrestamo() {
    }

    public NomDetaPrestamo(NomDetaPrestamoId id, String numCuo, BigDecimal valCuo, BigDecimal valAbo) {
       this.id = id;
       this.numCuo = numCuo;
       this.valCuo = valCuo;
       this.valAbo = valAbo;
    }
   
    public NomDetaPrestamoId getId() {
        return this.id;
    }
    
    public void setId(NomDetaPrestamoId id) {
        this.id = id;
    }
    public String getNumCuo() {
        return this.numCuo;
    }
    
    public void setNumCuo(String numCuo) {
        this.numCuo = numCuo;
    }
    public BigDecimal getValCuo() {
        return this.valCuo;
    }
    
    public void setValCuo(BigDecimal valCuo) {
        this.valCuo = valCuo;
    }
    public BigDecimal getValAbo() {
        return this.valAbo;
    }
    
    public void setValAbo(BigDecimal valAbo) {
        this.valAbo = valAbo;
    }




}


