package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * NomDetaVariables generated by hbm2java
 */
public class NomDetaVariables  implements java.io.Serializable {


     private NomDetaVariablesId id;
     private BigDecimal valVar;
     private String codVarG;

    public NomDetaVariables() {
    }

    public NomDetaVariables(NomDetaVariablesId id, BigDecimal valVar, String codVarG) {
       this.id = id;
       this.valVar = valVar;
       this.codVarG = codVarG;
    }
   
    public NomDetaVariablesId getId() {
        return this.id;
    }
    
    public void setId(NomDetaVariablesId id) {
        this.id = id;
    }
    public BigDecimal getValVar() {
        return this.valVar;
    }
    
    public void setValVar(BigDecimal valVar) {
        this.valVar = valVar;
    }
    public String getCodVarG() {
        return this.codVarG;
    }
    
    public void setCodVarG(String codVarG) {
        this.codVarG = codVarG;
    }




}


