package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * NomEps generated by hbm2java
 */
public class NomEps  implements java.io.Serializable {


     private String codEps;
     private String codTer;

    public NomEps() {
    }

    public NomEps(String codEps, String codTer) {
       this.codEps = codEps;
       this.codTer = codTer;
    }
   
    public String getCodEps() {
        return this.codEps;
    }
    
    public void setCodEps(String codEps) {
        this.codEps = codEps;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }




}


