package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * NomEmpleado generated by hbm2java
 */
public class NomEmpleado  implements java.io.Serializable {


     private String codEmp;
     private String codTer;
     private String codCos;
     private String codTerEps;
     private String codTerArp;
     private String codMarArp;
     private String codTerPen;
     private String codTerCes;
     private String codTerCja;
     private String codCargo;
     private String codTipoCon;
     private String codSec;
     private String codEst;
     private String codbanco;
     private String nomcta;
     private String numcta;
     private int tipcta;

    public NomEmpleado() {
    }

    public NomEmpleado(String codEmp, String codTer, String codCos, String codTerEps, String codTerArp, String codMarArp, String codTerPen, String codTerCes, String codTerCja, String codCargo, String codTipoCon, String codSec, String codEst, String codbanco, String nomcta, String numcta, int tipcta) {
       this.codEmp = codEmp;
       this.codTer = codTer;
       this.codCos = codCos;
       this.codTerEps = codTerEps;
       this.codTerArp = codTerArp;
       this.codMarArp = codMarArp;
       this.codTerPen = codTerPen;
       this.codTerCes = codTerCes;
       this.codTerCja = codTerCja;
       this.codCargo = codCargo;
       this.codTipoCon = codTipoCon;
       this.codSec = codSec;
       this.codEst = codEst;
       this.codbanco = codbanco;
       this.nomcta = nomcta;
       this.numcta = numcta;
       this.tipcta = tipcta;
    }
   
    public String getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(String codEmp) {
        this.codEmp = codEmp;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }
    public String getCodCos() {
        return this.codCos;
    }
    
    public void setCodCos(String codCos) {
        this.codCos = codCos;
    }
    public String getCodTerEps() {
        return this.codTerEps;
    }
    
    public void setCodTerEps(String codTerEps) {
        this.codTerEps = codTerEps;
    }
    public String getCodTerArp() {
        return this.codTerArp;
    }
    
    public void setCodTerArp(String codTerArp) {
        this.codTerArp = codTerArp;
    }
    public String getCodMarArp() {
        return this.codMarArp;
    }
    
    public void setCodMarArp(String codMarArp) {
        this.codMarArp = codMarArp;
    }
    public String getCodTerPen() {
        return this.codTerPen;
    }
    
    public void setCodTerPen(String codTerPen) {
        this.codTerPen = codTerPen;
    }
    public String getCodTerCes() {
        return this.codTerCes;
    }
    
    public void setCodTerCes(String codTerCes) {
        this.codTerCes = codTerCes;
    }
    public String getCodTerCja() {
        return this.codTerCja;
    }
    
    public void setCodTerCja(String codTerCja) {
        this.codTerCja = codTerCja;
    }
    public String getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(String codCargo) {
        this.codCargo = codCargo;
    }
    public String getCodTipoCon() {
        return this.codTipoCon;
    }
    
    public void setCodTipoCon(String codTipoCon) {
        this.codTipoCon = codTipoCon;
    }
    public String getCodSec() {
        return this.codSec;
    }
    
    public void setCodSec(String codSec) {
        this.codSec = codSec;
    }
    public String getCodEst() {
        return this.codEst;
    }
    
    public void setCodEst(String codEst) {
        this.codEst = codEst;
    }
    public String getCodbanco() {
        return this.codbanco;
    }
    
    public void setCodbanco(String codbanco) {
        this.codbanco = codbanco;
    }
    public String getNomcta() {
        return this.nomcta;
    }
    
    public void setNomcta(String nomcta) {
        this.nomcta = nomcta;
    }
    public String getNumcta() {
        return this.numcta;
    }
    
    public void setNumcta(String numcta) {
        this.numcta = numcta;
    }
    public int getTipcta() {
        return this.tipcta;
    }
    
    public void setTipcta(int tipcta) {
        this.tipcta = tipcta;
    }




}


