package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * NomHistorial generated by hbm2java
 */
public class NomHistorial  implements java.io.Serializable {


     private NomHistorialId id;
     private Date fecDoc;
     private String codSec;
     private String codTer;
     private BigDecimal qty;
     private BigDecimal vrUnitario;
     private BigDecimal devengado;
     private BigDecimal deducido;
     private String codCue;
     private String codAlmPre;
     private String numCuo;
     private String numPre;
     private BigDecimal ajusteP;

    public NomHistorial() {
    }

	
    public NomHistorial(NomHistorialId id, String codSec, String codTer, BigDecimal qty, BigDecimal vrUnitario, BigDecimal devengado, BigDecimal deducido, String codCue, String codAlmPre, String numCuo, String numPre, BigDecimal ajusteP) {
        this.id = id;
        this.codSec = codSec;
        this.codTer = codTer;
        this.qty = qty;
        this.vrUnitario = vrUnitario;
        this.devengado = devengado;
        this.deducido = deducido;
        this.codCue = codCue;
        this.codAlmPre = codAlmPre;
        this.numCuo = numCuo;
        this.numPre = numPre;
        this.ajusteP = ajusteP;
    }
    public NomHistorial(NomHistorialId id, Date fecDoc, String codSec, String codTer, BigDecimal qty, BigDecimal vrUnitario, BigDecimal devengado, BigDecimal deducido, String codCue, String codAlmPre, String numCuo, String numPre, BigDecimal ajusteP) {
       this.id = id;
       this.fecDoc = fecDoc;
       this.codSec = codSec;
       this.codTer = codTer;
       this.qty = qty;
       this.vrUnitario = vrUnitario;
       this.devengado = devengado;
       this.deducido = deducido;
       this.codCue = codCue;
       this.codAlmPre = codAlmPre;
       this.numCuo = numCuo;
       this.numPre = numPre;
       this.ajusteP = ajusteP;
    }
   
    public NomHistorialId getId() {
        return this.id;
    }
    
    public void setId(NomHistorialId id) {
        this.id = id;
    }
    public Date getFecDoc() {
        return this.fecDoc;
    }
    
    public void setFecDoc(Date fecDoc) {
        this.fecDoc = fecDoc;
    }
    public String getCodSec() {
        return this.codSec;
    }
    
    public void setCodSec(String codSec) {
        this.codSec = codSec;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }
    public BigDecimal getVrUnitario() {
        return this.vrUnitario;
    }
    
    public void setVrUnitario(BigDecimal vrUnitario) {
        this.vrUnitario = vrUnitario;
    }
    public BigDecimal getDevengado() {
        return this.devengado;
    }
    
    public void setDevengado(BigDecimal devengado) {
        this.devengado = devengado;
    }
    public BigDecimal getDeducido() {
        return this.deducido;
    }
    
    public void setDeducido(BigDecimal deducido) {
        this.deducido = deducido;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public String getCodAlmPre() {
        return this.codAlmPre;
    }
    
    public void setCodAlmPre(String codAlmPre) {
        this.codAlmPre = codAlmPre;
    }
    public String getNumCuo() {
        return this.numCuo;
    }
    
    public void setNumCuo(String numCuo) {
        this.numCuo = numCuo;
    }
    public String getNumPre() {
        return this.numPre;
    }
    
    public void setNumPre(String numPre) {
        this.numPre = numPre;
    }
    public BigDecimal getAjusteP() {
        return this.ajusteP;
    }
    
    public void setAjusteP(BigDecimal ajusteP) {
        this.ajusteP = ajusteP;
    }




}


