package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * NomNovedad generated by hbm2java
 */
public class NomNovedad  implements java.io.Serializable {


     private NomNovedadId id;
     private String codTrans;
     private int qty;
     private BigDecimal valor;

    public NomNovedad() {
    }

    public NomNovedad(NomNovedadId id, String codTrans, int qty, BigDecimal valor) {
       this.id = id;
       this.codTrans = codTrans;
       this.qty = qty;
       this.valor = valor;
    }
   
    public NomNovedadId getId() {
        return this.id;
    }
    
    public void setId(NomNovedadId id) {
        this.id = id;
    }
    public String getCodTrans() {
        return this.codTrans;
    }
    
    public void setCodTrans(String codTrans) {
        this.codTrans = codTrans;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


