package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * NomPension generated by hbm2java
 */
public class NomPension  implements java.io.Serializable {


     private String codPen;
     private String codTer;

    public NomPension() {
    }

    public NomPension(String codPen, String codTer) {
       this.codPen = codPen;
       this.codTer = codTer;
    }
   
    public String getCodPen() {
        return this.codPen;
    }
    
    public void setCodPen(String codPen) {
        this.codPen = codPen;
    }
    public String getCodTer() {
        return this.codTer;
    }
    
    public void setCodTer(String codTer) {
        this.codTer = codTer;
    }




}


