package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * NomPagos generated by hbm2java
 */
public class NomPagos  implements java.io.Serializable {


     private NomPagosId id;
     private Date fecDoc;
     private BigDecimal devengado;
     private BigDecimal deducido;
     private BigDecimal neto;
     private BigDecimal abonado;
     private long codReg;
     private String codCos;

    public NomPagos() {
    }

	
    public NomPagos(NomPagosId id, BigDecimal devengado, BigDecimal deducido, BigDecimal neto, BigDecimal abonado, long codReg, String codCos) {
        this.id = id;
        this.devengado = devengado;
        this.deducido = deducido;
        this.neto = neto;
        this.abonado = abonado;
        this.codReg = codReg;
        this.codCos = codCos;
    }
    public NomPagos(NomPagosId id, Date fecDoc, BigDecimal devengado, BigDecimal deducido, BigDecimal neto, BigDecimal abonado, long codReg, String codCos) {
       this.id = id;
       this.fecDoc = fecDoc;
       this.devengado = devengado;
       this.deducido = deducido;
       this.neto = neto;
       this.abonado = abonado;
       this.codReg = codReg;
       this.codCos = codCos;
    }
   
    public NomPagosId getId() {
        return this.id;
    }
    
    public void setId(NomPagosId id) {
        this.id = id;
    }
    public Date getFecDoc() {
        return this.fecDoc;
    }
    
    public void setFecDoc(Date fecDoc) {
        this.fecDoc = fecDoc;
    }
    public BigDecimal getDevengado() {
        return this.devengado;
    }
    
    public void setDevengado(BigDecimal devengado) {
        this.devengado = devengado;
    }
    public BigDecimal getDeducido() {
        return this.deducido;
    }
    
    public void setDeducido(BigDecimal deducido) {
        this.deducido = deducido;
    }
    public BigDecimal getNeto() {
        return this.neto;
    }
    
    public void setNeto(BigDecimal neto) {
        this.neto = neto;
    }
    public BigDecimal getAbonado() {
        return this.abonado;
    }
    
    public void setAbonado(BigDecimal abonado) {
        this.abonado = abonado;
    }
    public long getCodReg() {
        return this.codReg;
    }
    
    public void setCodReg(long codReg) {
        this.codReg = codReg;
    }
    public String getCodCos() {
        return this.codCos;
    }
    
    public void setCodCos(String codCos) {
        this.codCos = codCos;
    }




}


