package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * NomPeriodosxVar generated by hbm2java
 */
public class NomPeriodosxVar  implements java.io.Serializable {


     private NomPeriodosxVarId id;

    public NomPeriodosxVar() {
    }

    public NomPeriodosxVar(NomPeriodosxVarId id) {
       this.id = id;
    }
   
    public NomPeriodosxVarId getId() {
        return this.id;
    }
    
    public void setId(NomPeriodosxVarId id) {
        this.id = id;
    }




}


