package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * NomTipoContrato generated by hbm2java
 */
public class NomTipoContrato  implements java.io.Serializable {


     private String codTipoCon;
     private String nomTipo;
     private boolean liqArp;
     private boolean liqCajaComp;
     private boolean liqCesantia;
     private boolean liqIcbf;
     private boolean liqIcesantia;
     private boolean liqPension;
     private boolean liqPrimas;
     private boolean liqSalud;
     private boolean liqSena;
     private boolean liqVacaciones;

    public NomTipoContrato() {
    }

    public NomTipoContrato(String codTipoCon, String nomTipo, boolean liqArp, boolean liqCajaComp, boolean liqCesantia, boolean liqIcbf, boolean liqIcesantia, boolean liqPension, boolean liqPrimas, boolean liqSalud, boolean liqSena, boolean liqVacaciones) {
       this.codTipoCon = codTipoCon;
       this.nomTipo = nomTipo;
       this.liqArp = liqArp;
       this.liqCajaComp = liqCajaComp;
       this.liqCesantia = liqCesantia;
       this.liqIcbf = liqIcbf;
       this.liqIcesantia = liqIcesantia;
       this.liqPension = liqPension;
       this.liqPrimas = liqPrimas;
       this.liqSalud = liqSalud;
       this.liqSena = liqSena;
       this.liqVacaciones = liqVacaciones;
    }
   
    public String getCodTipoCon() {
        return this.codTipoCon;
    }
    
    public void setCodTipoCon(String codTipoCon) {
        this.codTipoCon = codTipoCon;
    }
    public String getNomTipo() {
        return this.nomTipo;
    }
    
    public void setNomTipo(String nomTipo) {
        this.nomTipo = nomTipo;
    }
    public boolean isLiqArp() {
        return this.liqArp;
    }
    
    public void setLiqArp(boolean liqArp) {
        this.liqArp = liqArp;
    }
    public boolean isLiqCajaComp() {
        return this.liqCajaComp;
    }
    
    public void setLiqCajaComp(boolean liqCajaComp) {
        this.liqCajaComp = liqCajaComp;
    }
    public boolean isLiqCesantia() {
        return this.liqCesantia;
    }
    
    public void setLiqCesantia(boolean liqCesantia) {
        this.liqCesantia = liqCesantia;
    }
    public boolean isLiqIcbf() {
        return this.liqIcbf;
    }
    
    public void setLiqIcbf(boolean liqIcbf) {
        this.liqIcbf = liqIcbf;
    }
    public boolean isLiqIcesantia() {
        return this.liqIcesantia;
    }
    
    public void setLiqIcesantia(boolean liqIcesantia) {
        this.liqIcesantia = liqIcesantia;
    }
    public boolean isLiqPension() {
        return this.liqPension;
    }
    
    public void setLiqPension(boolean liqPension) {
        this.liqPension = liqPension;
    }
    public boolean isLiqPrimas() {
        return this.liqPrimas;
    }
    
    public void setLiqPrimas(boolean liqPrimas) {
        this.liqPrimas = liqPrimas;
    }
    public boolean isLiqSalud() {
        return this.liqSalud;
    }
    
    public void setLiqSalud(boolean liqSalud) {
        this.liqSalud = liqSalud;
    }
    public boolean isLiqSena() {
        return this.liqSena;
    }
    
    public void setLiqSena(boolean liqSena) {
        this.liqSena = liqSena;
    }
    public boolean isLiqVacaciones() {
        return this.liqVacaciones;
    }
    
    public void setLiqVacaciones(boolean liqVacaciones) {
        this.liqVacaciones = liqVacaciones;
    }




}


