package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * NomTipoArp generated by hbm2java
 */
public class NomTipoArp  implements java.io.Serializable {


     private String codMar;
     private String nomMar;
     private BigDecimal margen;
     private boolean sistema;

    public NomTipoArp() {
    }

    public NomTipoArp(String codMar, String nomMar, BigDecimal margen, boolean sistema) {
       this.codMar = codMar;
       this.nomMar = nomMar;
       this.margen = margen;
       this.sistema = sistema;
    }
   
    public String getCodMar() {
        return this.codMar;
    }
    
    public void setCodMar(String codMar) {
        this.codMar = codMar;
    }
    public String getNomMar() {
        return this.nomMar;
    }
    
    public void setNomMar(String nomMar) {
        this.nomMar = nomMar;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }
    public boolean isSistema() {
        return this.sistema;
    }
    
    public void setSistema(boolean sistema) {
        this.sistema = sistema;
    }




}


