package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * NomTransxVar generated by hbm2java
 */
public class NomTransxVar  implements java.io.Serializable {


     private NomTransxVarId id;

    public NomTransxVar() {
    }

    public NomTransxVar(NomTransxVarId id) {
       this.id = id;
    }
   
    public NomTransxVarId getId() {
        return this.id;
    }
    
    public void setId(NomTransxVarId id) {
        this.id = id;
    }




}


