package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * NomTransxEmpId generated by hbm2java
 */
public class NomTransxEmpId  implements java.io.Serializable {


     private String codEmp;
     private String codTran;

    public NomTransxEmpId() {
    }

    public NomTransxEmpId(String codEmp, String codTran) {
       this.codEmp = codEmp;
       this.codTran = codTran;
    }
   
    public String getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(String codEmp) {
        this.codEmp = codEmp;
    }
    public String getCodTran() {
        return this.codTran;
    }
    
    public void setCodTran(String codTran) {
        this.codTran = codTran;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NomTransxEmpId) ) return false;
		 NomTransxEmpId castOther = ( NomTransxEmpId ) other; 
         
		 return ( (this.getCodEmp()==castOther.getCodEmp()) || ( this.getCodEmp()!=null && castOther.getCodEmp()!=null && this.getCodEmp().equals(castOther.getCodEmp()) ) )
 && ( (this.getCodTran()==castOther.getCodTran()) || ( this.getCodTran()!=null && castOther.getCodTran()!=null && this.getCodTran().equals(castOther.getCodTran()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodEmp() == null ? 0 : this.getCodEmp().hashCode() );
         result = 37 * result + ( getCodTran() == null ? 0 : this.getCodTran().hashCode() );
         return result;
   }   


}


