package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * PelDctoxServ generated by hbm2java
 */
public class PelDctoxServ  implements java.io.Serializable {


     private PelDctoxServId id;
     private BigDecimal valInv;
     private BigDecimal valor;

    public PelDctoxServ() {
    }

    public PelDctoxServ(PelDctoxServId id, BigDecimal valInv, BigDecimal valor) {
       this.id = id;
       this.valInv = valInv;
       this.valor = valor;
    }
   
    public PelDctoxServId getId() {
        return this.id;
    }
    
    public void setId(PelDctoxServId id) {
        this.id = id;
    }
    public BigDecimal getValInv() {
        return this.valInv;
    }
    
    public void setValInv(BigDecimal valInv) {
        this.valInv = valInv;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


