package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * SysAlmConceptos generated by hbm2java
 */
public class SysAlmConceptos  implements java.io.Serializable {


     private String codcon;
     private String codAnu;
     private String nomcon;
     private Character tipcon;
     private Boolean sistema;
     private boolean userTransaction;
     private boolean anulacion;
     private String codCue;
     private boolean modificado;

    public SysAlmConceptos() {
    }

	
    public SysAlmConceptos(String codcon, String codAnu, boolean userTransaction, boolean anulacion, String codCue, boolean modificado) {
        this.codcon = codcon;
        this.codAnu = codAnu;
        this.userTransaction = userTransaction;
        this.anulacion = anulacion;
        this.codCue = codCue;
        this.modificado = modificado;
    }
    public SysAlmConceptos(String codcon, String codAnu, String nomcon, Character tipcon, Boolean sistema, boolean userTransaction, boolean anulacion, String codCue, boolean modificado) {
       this.codcon = codcon;
       this.codAnu = codAnu;
       this.nomcon = nomcon;
       this.tipcon = tipcon;
       this.sistema = sistema;
       this.userTransaction = userTransaction;
       this.anulacion = anulacion;
       this.codCue = codCue;
       this.modificado = modificado;
    }
   
    public String getCodcon() {
        return this.codcon;
    }
    
    public void setCodcon(String codcon) {
        this.codcon = codcon;
    }
    public String getCodAnu() {
        return this.codAnu;
    }
    
    public void setCodAnu(String codAnu) {
        this.codAnu = codAnu;
    }
    public String getNomcon() {
        return this.nomcon;
    }
    
    public void setNomcon(String nomcon) {
        this.nomcon = nomcon;
    }
    public Character getTipcon() {
        return this.tipcon;
    }
    
    public void setTipcon(Character tipcon) {
        this.tipcon = tipcon;
    }
    public Boolean getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Boolean sistema) {
        this.sistema = sistema;
    }
    public boolean isUserTransaction() {
        return this.userTransaction;
    }
    
    public void setUserTransaction(boolean userTransaction) {
        this.userTransaction = userTransaction;
    }
    public boolean isAnulacion() {
        return this.anulacion;
    }
    
    public void setAnulacion(boolean anulacion) {
        this.anulacion = anulacion;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }




}


