package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * TesCtasBancariasxAlm generated by hbm2java
 */
public class TesCtasBancariasxAlm  implements java.io.Serializable {


     private TesCtasBancariasxAlmId id;

    public TesCtasBancariasxAlm() {
    }

    public TesCtasBancariasxAlm(TesCtasBancariasxAlmId id) {
       this.id = id;
    }
   
    public TesCtasBancariasxAlmId getId() {
        return this.id;
    }
    
    public void setId(TesCtasBancariasxAlmId id) {
        this.id = id;
    }




}


