package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * TesCajas generated by hbm2java
 */
public class TesCajas  implements java.io.Serializable {


     private String codCaja;
     private String nomcaja;
     private String ctaEfectivo;
     private String ctaCheques;
     private String ctaTarjetas;
     private String estado;
     private boolean modificado;
     private boolean cajaPpal;
     private String estacion;
     private String cedula;
     private boolean cajamenor;
     private boolean requierecuadre;
     private BigDecimal cupocm;
     private boolean autoTransfer;
     private String codCajaTransfer;
     private boolean auxiliar;
     private String codCajaPadre;
     private boolean ajustaSaldo;

    public TesCajas() {
    }

	
    public TesCajas(String codCaja, String ctaEfectivo, String ctaCheques, String ctaTarjetas, String estado, boolean modificado, boolean cajaPpal, String estacion, String cedula, boolean cajamenor, boolean requierecuadre, BigDecimal cupocm, boolean autoTransfer, String codCajaTransfer, boolean auxiliar, String codCajaPadre, boolean ajustaSaldo) {
        this.codCaja = codCaja;
        this.ctaEfectivo = ctaEfectivo;
        this.ctaCheques = ctaCheques;
        this.ctaTarjetas = ctaTarjetas;
        this.estado = estado;
        this.modificado = modificado;
        this.cajaPpal = cajaPpal;
        this.estacion = estacion;
        this.cedula = cedula;
        this.cajamenor = cajamenor;
        this.requierecuadre = requierecuadre;
        this.cupocm = cupocm;
        this.autoTransfer = autoTransfer;
        this.codCajaTransfer = codCajaTransfer;
        this.auxiliar = auxiliar;
        this.codCajaPadre = codCajaPadre;
        this.ajustaSaldo = ajustaSaldo;
    }
    public TesCajas(String codCaja, String nomcaja, String ctaEfectivo, String ctaCheques, String ctaTarjetas, String estado, boolean modificado, boolean cajaPpal, String estacion, String cedula, boolean cajamenor, boolean requierecuadre, BigDecimal cupocm, boolean autoTransfer, String codCajaTransfer, boolean auxiliar, String codCajaPadre, boolean ajustaSaldo) {
       this.codCaja = codCaja;
       this.nomcaja = nomcaja;
       this.ctaEfectivo = ctaEfectivo;
       this.ctaCheques = ctaCheques;
       this.ctaTarjetas = ctaTarjetas;
       this.estado = estado;
       this.modificado = modificado;
       this.cajaPpal = cajaPpal;
       this.estacion = estacion;
       this.cedula = cedula;
       this.cajamenor = cajamenor;
       this.requierecuadre = requierecuadre;
       this.cupocm = cupocm;
       this.autoTransfer = autoTransfer;
       this.codCajaTransfer = codCajaTransfer;
       this.auxiliar = auxiliar;
       this.codCajaPadre = codCajaPadre;
       this.ajustaSaldo = ajustaSaldo;
    }
   
    public String getCodCaja() {
        return this.codCaja;
    }
    
    public void setCodCaja(String codCaja) {
        this.codCaja = codCaja;
    }
    public String getNomcaja() {
        return this.nomcaja;
    }
    
    public void setNomcaja(String nomcaja) {
        this.nomcaja = nomcaja;
    }
    public String getCtaEfectivo() {
        return this.ctaEfectivo;
    }
    
    public void setCtaEfectivo(String ctaEfectivo) {
        this.ctaEfectivo = ctaEfectivo;
    }
    public String getCtaCheques() {
        return this.ctaCheques;
    }
    
    public void setCtaCheques(String ctaCheques) {
        this.ctaCheques = ctaCheques;
    }
    public String getCtaTarjetas() {
        return this.ctaTarjetas;
    }
    
    public void setCtaTarjetas(String ctaTarjetas) {
        this.ctaTarjetas = ctaTarjetas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public boolean isCajaPpal() {
        return this.cajaPpal;
    }
    
    public void setCajaPpal(boolean cajaPpal) {
        this.cajaPpal = cajaPpal;
    }
    public String getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(String estacion) {
        this.estacion = estacion;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public boolean isCajamenor() {
        return this.cajamenor;
    }
    
    public void setCajamenor(boolean cajamenor) {
        this.cajamenor = cajamenor;
    }
    public boolean isRequierecuadre() {
        return this.requierecuadre;
    }
    
    public void setRequierecuadre(boolean requierecuadre) {
        this.requierecuadre = requierecuadre;
    }
    public BigDecimal getCupocm() {
        return this.cupocm;
    }
    
    public void setCupocm(BigDecimal cupocm) {
        this.cupocm = cupocm;
    }
    public boolean isAutoTransfer() {
        return this.autoTransfer;
    }
    
    public void setAutoTransfer(boolean autoTransfer) {
        this.autoTransfer = autoTransfer;
    }
    public String getCodCajaTransfer() {
        return this.codCajaTransfer;
    }
    
    public void setCodCajaTransfer(String codCajaTransfer) {
        this.codCajaTransfer = codCajaTransfer;
    }
    public boolean isAuxiliar() {
        return this.auxiliar;
    }
    
    public void setAuxiliar(boolean auxiliar) {
        this.auxiliar = auxiliar;
    }
    public String getCodCajaPadre() {
        return this.codCajaPadre;
    }
    
    public void setCodCajaPadre(String codCajaPadre) {
        this.codCajaPadre = codCajaPadre;
    }
    public boolean isAjustaSaldo() {
        return this.ajustaSaldo;
    }
    
    public void setAjustaSaldo(boolean ajustaSaldo) {
        this.ajustaSaldo = ajustaSaldo;
    }




}


