package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * TesCtasBancariasxUsuId generated by hbm2java
 */
public class TesCtasBancariasxUsuId  implements java.io.Serializable {


     private String codCta;
     private String codUsu;

    public TesCtasBancariasxUsuId() {
    }

    public TesCtasBancariasxUsuId(String codCta, String codUsu) {
       this.codCta = codCta;
       this.codUsu = codUsu;
    }
   
    public String getCodCta() {
        return this.codCta;
    }
    
    public void setCodCta(String codCta) {
        this.codCta = codCta;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TesCtasBancariasxUsuId) ) return false;
		 TesCtasBancariasxUsuId castOther = ( TesCtasBancariasxUsuId ) other; 
         
		 return ( (this.getCodCta()==castOther.getCodCta()) || ( this.getCodCta()!=null && castOther.getCodCta()!=null && this.getCodCta().equals(castOther.getCodCta()) ) )
 && ( (this.getCodUsu()==castOther.getCodUsu()) || ( this.getCodUsu()!=null && castOther.getCodUsu()!=null && this.getCodUsu().equals(castOther.getCodUsu()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCta() == null ? 0 : this.getCodCta().hashCode() );
         result = 37 * result + ( getCodUsu() == null ? 0 : this.getCodUsu().hashCode() );
         return result;
   }   


}


