package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * TesCtasBancariasxUsu generated by hbm2java
 */
public class TesCtasBancariasxUsu  implements java.io.Serializable {


     private TesCtasBancariasxUsuId id;

    public TesCtasBancariasxUsu() {
    }

    public TesCtasBancariasxUsu(TesCtasBancariasxUsuId id) {
       this.id = id;
    }
   
    public TesCtasBancariasxUsuId getId() {
        return this.id;
    }
    
    public void setId(TesCtasBancariasxUsuId id) {
        this.id = id;
    }




}


