package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * TesCargosxRc generated by hbm2java
 */
public class TesCargosxRc  implements java.io.Serializable {


     private TesCargosxRcId id;
     private BigDecimal base;
     private BigDecimal margen;
     private BigDecimal valor;

    public TesCargosxRc() {
    }

    public TesCargosxRc(TesCargosxRcId id, BigDecimal base, BigDecimal margen, BigDecimal valor) {
       this.id = id;
       this.base = base;
       this.margen = margen;
       this.valor = valor;
    }
   
    public TesCargosxRcId getId() {
        return this.id;
    }
    
    public void setId(TesCargosxRcId id) {
        this.id = id;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


