package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * TesCajasxUsu generated by hbm2java
 */
public class TesCajasxUsu  implements java.io.Serializable {


     private TesCajasxUsuId id;

    public TesCajasxUsu() {
    }

    public TesCajasxUsu(TesCajasxUsuId id) {
       this.id = id;
    }
   
    public TesCajasxUsuId getId() {
        return this.id;
    }
    
    public void setId(TesCajasxUsuId id) {
        this.id = id;
    }




}


