package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * TesCtasBancarias generated by hbm2java
 */
public class TesCtasBancarias  implements java.io.Serializable {


     private String codCta;
     private char tipoCta;
     private String numCta;
     private String codcue;
     private boolean activa;
     private String nomcta;
     private boolean modificado;
     private String codmon;
     private String refcta;
     private int orden;

    public TesCtasBancarias() {
    }

    public TesCtasBancarias(String codCta, char tipoCta, String numCta, String codcue, boolean activa, String nomcta, boolean modificado, String codmon, String refcta, int orden) {
       this.codCta = codCta;
       this.tipoCta = tipoCta;
       this.numCta = numCta;
       this.codcue = codcue;
       this.activa = activa;
       this.nomcta = nomcta;
       this.modificado = modificado;
       this.codmon = codmon;
       this.refcta = refcta;
       this.orden = orden;
    }
   
    public String getCodCta() {
        return this.codCta;
    }
    
    public void setCodCta(String codCta) {
        this.codCta = codCta;
    }
    public char getTipoCta() {
        return this.tipoCta;
    }
    
    public void setTipoCta(char tipoCta) {
        this.tipoCta = tipoCta;
    }
    public String getNumCta() {
        return this.numCta;
    }
    
    public void setNumCta(String numCta) {
        this.numCta = numCta;
    }
    public String getCodcue() {
        return this.codcue;
    }
    
    public void setCodcue(String codcue) {
        this.codcue = codcue;
    }
    public boolean isActiva() {
        return this.activa;
    }
    
    public void setActiva(boolean activa) {
        this.activa = activa;
    }
    public String getNomcta() {
        return this.nomcta;
    }
    
    public void setNomcta(String nomcta) {
        this.nomcta = nomcta;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public String getCodmon() {
        return this.codmon;
    }
    
    public void setCodmon(String codmon) {
        this.codmon = codmon;
    }
    public String getRefcta() {
        return this.refcta;
    }
    
    public void setRefcta(String refcta) {
        this.refcta = refcta;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


