package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * TesConceptosNb generated by hbm2java
 */
public class TesConceptosNb  implements java.io.Serializable {


     private String codCon;
     private String nomCon;
     private String codCue;
     private char tipCon;
     private boolean modificado;

    public TesConceptosNb() {
    }

    public TesConceptosNb(String codCon, String nomCon, String codCue, char tipCon, boolean modificado) {
       this.codCon = codCon;
       this.nomCon = nomCon;
       this.codCue = codCue;
       this.tipCon = tipCon;
       this.modificado = modificado;
    }
   
    public String getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(String codCon) {
        this.codCon = codCon;
    }
    public String getNomCon() {
        return this.nomCon;
    }
    
    public void setNomCon(String nomCon) {
        this.nomCon = nomCon;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public char getTipCon() {
        return this.tipCon;
    }
    
    public void setTipCon(char tipCon) {
        this.tipCon = tipCon;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }




}


