package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TesDetaChequeras generated by hbm2java
 */
public class TesDetaChequeras  implements java.io.Serializable {


     private TesDetaChequerasId id;
     private String codAlm;
     private String tipEgr;
     private String numEgr;
     private String observa;
     private Date fechachq;

    public TesDetaChequeras() {
    }

    public TesDetaChequeras(TesDetaChequerasId id, String codAlm, String tipEgr, String numEgr, String observa, Date fechachq) {
       this.id = id;
       this.codAlm = codAlm;
       this.tipEgr = tipEgr;
       this.numEgr = numEgr;
       this.observa = observa;
       this.fechachq = fechachq;
    }
   
    public TesDetaChequerasId getId() {
        return this.id;
    }
    
    public void setId(TesDetaChequerasId id) {
        this.id = id;
    }
    public String getCodAlm() {
        return this.codAlm;
    }
    
    public void setCodAlm(String codAlm) {
        this.codAlm = codAlm;
    }
    public String getTipEgr() {
        return this.tipEgr;
    }
    
    public void setTipEgr(String tipEgr) {
        this.tipEgr = tipEgr;
    }
    public String getNumEgr() {
        return this.numEgr;
    }
    
    public void setNumEgr(String numEgr) {
        this.numEgr = numEgr;
    }
    public String getObserva() {
        return this.observa;
    }
    
    public void setObserva(String observa) {
        this.observa = observa;
    }
    public Date getFechachq() {
        return this.fechachq;
    }
    
    public void setFechachq(Date fechachq) {
        this.fechachq = fechachq;
    }




}


