package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * TesDetaChequerasId generated by hbm2java
 */
public class TesDetaChequerasId  implements java.io.Serializable {


     private String codCta;
     private String codChq;
     private String numChq;

    public TesDetaChequerasId() {
    }

    public TesDetaChequerasId(String codCta, String codChq, String numChq) {
       this.codCta = codCta;
       this.codChq = codChq;
       this.numChq = numChq;
    }
   
    public String getCodCta() {
        return this.codCta;
    }
    
    public void setCodCta(String codCta) {
        this.codCta = codCta;
    }
    public String getCodChq() {
        return this.codChq;
    }
    
    public void setCodChq(String codChq) {
        this.codChq = codChq;
    }
    public String getNumChq() {
        return this.numChq;
    }
    
    public void setNumChq(String numChq) {
        this.numChq = numChq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TesDetaChequerasId) ) return false;
		 TesDetaChequerasId castOther = ( TesDetaChequerasId ) other; 
         
		 return ( (this.getCodCta()==castOther.getCodCta()) || ( this.getCodCta()!=null && castOther.getCodCta()!=null && this.getCodCta().equals(castOther.getCodCta()) ) )
 && ( (this.getCodChq()==castOther.getCodChq()) || ( this.getCodChq()!=null && castOther.getCodChq()!=null && this.getCodChq().equals(castOther.getCodChq()) ) )
 && ( (this.getNumChq()==castOther.getNumChq()) || ( this.getNumChq()!=null && castOther.getNumChq()!=null && this.getNumChq().equals(castOther.getNumChq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCta() == null ? 0 : this.getCodCta().hashCode() );
         result = 37 * result + ( getCodChq() == null ? 0 : this.getCodChq().hashCode() );
         result = 37 * result + ( getNumChq() == null ? 0 : this.getNumChq().hashCode() );
         return result;
   }   


}


