package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TesEgresos generated by hbm2java
 */
public class TesEgresos  implements java.io.Serializable {


     private TesEgresosId id;
     private String codCaja;
     private String codCta;
     private String codChq;
     private String numChq;
     private BigDecimal valEgr;
     private Date fecEgr;
     private String codter;
     private Date fecSys;
     private String codUsu;
     private char estEgr;
     private char clase;
     private char fp;
     private String tipEgr;
     private BigDecimal valSobra;
     private BigDecimal valFalta;
     private String numTurno;
     private boolean egrcuadre;
     private BigDecimal valsubtotalegr;
     private BigDecimal valotregr;
     private BigDecimal valdctoegr;
     private BigDecimal valretegr;
     private String docfisico;
     private String codmon;
     private BigDecimal valant;

    public TesEgresos() {
    }

    public TesEgresos(TesEgresosId id, String codCaja, String codCta, String codChq, String numChq, BigDecimal valEgr, Date fecEgr, String codter, Date fecSys, String codUsu, char estEgr, char clase, char fp, String tipEgr, BigDecimal valSobra, BigDecimal valFalta, String numTurno, boolean egrcuadre, BigDecimal valsubtotalegr, BigDecimal valotregr, BigDecimal valdctoegr, BigDecimal valretegr, String docfisico, String codmon, BigDecimal valant) {
       this.id = id;
       this.codCaja = codCaja;
       this.codCta = codCta;
       this.codChq = codChq;
       this.numChq = numChq;
       this.valEgr = valEgr;
       this.fecEgr = fecEgr;
       this.codter = codter;
       this.fecSys = fecSys;
       this.codUsu = codUsu;
       this.estEgr = estEgr;
       this.clase = clase;
       this.fp = fp;
       this.tipEgr = tipEgr;
       this.valSobra = valSobra;
       this.valFalta = valFalta;
       this.numTurno = numTurno;
       this.egrcuadre = egrcuadre;
       this.valsubtotalegr = valsubtotalegr;
       this.valotregr = valotregr;
       this.valdctoegr = valdctoegr;
       this.valretegr = valretegr;
       this.docfisico = docfisico;
       this.codmon = codmon;
       this.valant = valant;
    }
   
    public TesEgresosId getId() {
        return this.id;
    }
    
    public void setId(TesEgresosId id) {
        this.id = id;
    }
    public String getCodCaja() {
        return this.codCaja;
    }
    
    public void setCodCaja(String codCaja) {
        this.codCaja = codCaja;
    }
    public String getCodCta() {
        return this.codCta;
    }
    
    public void setCodCta(String codCta) {
        this.codCta = codCta;
    }
    public String getCodChq() {
        return this.codChq;
    }
    
    public void setCodChq(String codChq) {
        this.codChq = codChq;
    }
    public String getNumChq() {
        return this.numChq;
    }
    
    public void setNumChq(String numChq) {
        this.numChq = numChq;
    }
    public BigDecimal getValEgr() {
        return this.valEgr;
    }
    
    public void setValEgr(BigDecimal valEgr) {
        this.valEgr = valEgr;
    }
    public Date getFecEgr() {
        return this.fecEgr;
    }
    
    public void setFecEgr(Date fecEgr) {
        this.fecEgr = fecEgr;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public char getEstEgr() {
        return this.estEgr;
    }
    
    public void setEstEgr(char estEgr) {
        this.estEgr = estEgr;
    }
    public char getClase() {
        return this.clase;
    }
    
    public void setClase(char clase) {
        this.clase = clase;
    }
    public char getFp() {
        return this.fp;
    }
    
    public void setFp(char fp) {
        this.fp = fp;
    }
    public String getTipEgr() {
        return this.tipEgr;
    }
    
    public void setTipEgr(String tipEgr) {
        this.tipEgr = tipEgr;
    }
    public BigDecimal getValSobra() {
        return this.valSobra;
    }
    
    public void setValSobra(BigDecimal valSobra) {
        this.valSobra = valSobra;
    }
    public BigDecimal getValFalta() {
        return this.valFalta;
    }
    
    public void setValFalta(BigDecimal valFalta) {
        this.valFalta = valFalta;
    }
    public String getNumTurno() {
        return this.numTurno;
    }
    
    public void setNumTurno(String numTurno) {
        this.numTurno = numTurno;
    }
    public boolean isEgrcuadre() {
        return this.egrcuadre;
    }
    
    public void setEgrcuadre(boolean egrcuadre) {
        this.egrcuadre = egrcuadre;
    }
    public BigDecimal getValsubtotalegr() {
        return this.valsubtotalegr;
    }
    
    public void setValsubtotalegr(BigDecimal valsubtotalegr) {
        this.valsubtotalegr = valsubtotalegr;
    }
    public BigDecimal getValotregr() {
        return this.valotregr;
    }
    
    public void setValotregr(BigDecimal valotregr) {
        this.valotregr = valotregr;
    }
    public BigDecimal getValdctoegr() {
        return this.valdctoegr;
    }
    
    public void setValdctoegr(BigDecimal valdctoegr) {
        this.valdctoegr = valdctoegr;
    }
    public BigDecimal getValretegr() {
        return this.valretegr;
    }
    
    public void setValretegr(BigDecimal valretegr) {
        this.valretegr = valretegr;
    }
    public String getDocfisico() {
        return this.docfisico;
    }
    
    public void setDocfisico(String docfisico) {
        this.docfisico = docfisico;
    }
    public String getCodmon() {
        return this.codmon;
    }
    
    public void setCodmon(String codmon) {
        this.codmon = codmon;
    }
    public BigDecimal getValant() {
        return this.valant;
    }
    
    public void setValant(BigDecimal valant) {
        this.valant = valant;
    }




}


