package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TesReciConceptos generated by hbm2java
 */
public class TesReciConceptos  implements java.io.Serializable {


     private String codcon;
     private String nomcon;
     private char tipCon;
     private String codCue;
     private String codUsu;
     private Date fecSys;
     private boolean sistema;
     private boolean aplicaMargen;
     private BigDecimal margen;
     private int baseMargen;
     private boolean modificado;

    public TesReciConceptos() {
    }

    public TesReciConceptos(String codcon, String nomcon, char tipCon, String codCue, String codUsu, Date fecSys, boolean sistema, boolean aplicaMargen, BigDecimal margen, int baseMargen, boolean modificado) {
       this.codcon = codcon;
       this.nomcon = nomcon;
       this.tipCon = tipCon;
       this.codCue = codCue;
       this.codUsu = codUsu;
       this.fecSys = fecSys;
       this.sistema = sistema;
       this.aplicaMargen = aplicaMargen;
       this.margen = margen;
       this.baseMargen = baseMargen;
       this.modificado = modificado;
    }
   
    public String getCodcon() {
        return this.codcon;
    }
    
    public void setCodcon(String codcon) {
        this.codcon = codcon;
    }
    public String getNomcon() {
        return this.nomcon;
    }
    
    public void setNomcon(String nomcon) {
        this.nomcon = nomcon;
    }
    public char getTipCon() {
        return this.tipCon;
    }
    
    public void setTipCon(char tipCon) {
        this.tipCon = tipCon;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public boolean isSistema() {
        return this.sistema;
    }
    
    public void setSistema(boolean sistema) {
        this.sistema = sistema;
    }
    public boolean isAplicaMargen() {
        return this.aplicaMargen;
    }
    
    public void setAplicaMargen(boolean aplicaMargen) {
        this.aplicaMargen = aplicaMargen;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }
    public int getBaseMargen() {
        return this.baseMargen;
    }
    
    public void setBaseMargen(int baseMargen) {
        this.baseMargen = baseMargen;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }




}


