package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * VenBasesRetId generated by hbm2java
 */
public class VenBasesRetId  implements java.io.Serializable {


     private String codCon;
     private String regPropiet;

    public VenBasesRetId() {
    }

    public VenBasesRetId(String codCon, String regPropiet) {
       this.codCon = codCon;
       this.regPropiet = regPropiet;
    }
   
    public String getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(String codCon) {
        this.codCon = codCon;
    }
    public String getRegPropiet() {
        return this.regPropiet;
    }
    
    public void setRegPropiet(String regPropiet) {
        this.regPropiet = regPropiet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VenBasesRetId) ) return false;
		 VenBasesRetId castOther = ( VenBasesRetId ) other; 
         
		 return ( (this.getCodCon()==castOther.getCodCon()) || ( this.getCodCon()!=null && castOther.getCodCon()!=null && this.getCodCon().equals(castOther.getCodCon()) ) )
 && ( (this.getRegPropiet()==castOther.getRegPropiet()) || ( this.getRegPropiet()!=null && castOther.getRegPropiet()!=null && this.getRegPropiet().equals(castOther.getRegPropiet()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodCon() == null ? 0 : this.getCodCon().hashCode() );
         result = 37 * result + ( getRegPropiet() == null ? 0 : this.getRegPropiet().hashCode() );
         return result;
   }   


}


