package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * VenClientesSucursal generated by hbm2java
 */
public class VenClientesSucursal  implements java.io.Serializable {


     private VenClientesSucursalId id;
     private String codMcpio;
     private String codDpto;
     private String telefono1;
     private String telefono2;
     private String celular1;
     private String celular2;
     private String direccion;
     private String tels;
     private String referencia;
     private boolean aplicaReteIca;

    public VenClientesSucursal() {
    }

    public VenClientesSucursal(VenClientesSucursalId id, String codMcpio, String codDpto, String telefono1, String telefono2, String celular1, String celular2, String direccion, String tels, String referencia, boolean aplicaReteIca) {
       this.id = id;
       this.codMcpio = codMcpio;
       this.codDpto = codDpto;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.celular1 = celular1;
       this.celular2 = celular2;
       this.direccion = direccion;
       this.tels = tels;
       this.referencia = referencia;
       this.aplicaReteIca = aplicaReteIca;
    }
   
    public VenClientesSucursalId getId() {
        return this.id;
    }
    
    public void setId(VenClientesSucursalId id) {
        this.id = id;
    }
    public String getCodMcpio() {
        return this.codMcpio;
    }
    
    public void setCodMcpio(String codMcpio) {
        this.codMcpio = codMcpio;
    }
    public String getCodDpto() {
        return this.codDpto;
    }
    
    public void setCodDpto(String codDpto) {
        this.codDpto = codDpto;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getCelular1() {
        return this.celular1;
    }
    
    public void setCelular1(String celular1) {
        this.celular1 = celular1;
    }
    public String getCelular2() {
        return this.celular2;
    }
    
    public void setCelular2(String celular2) {
        this.celular2 = celular2;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTels() {
        return this.tels;
    }
    
    public void setTels(String tels) {
        this.tels = tels;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public boolean isAplicaReteIca() {
        return this.aplicaReteIca;
    }
    
    public void setAplicaReteIca(boolean aplicaReteIca) {
        this.aplicaReteIca = aplicaReteIca;
    }




}


