package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * VenConceptosNotas generated by hbm2java
 */
public class VenConceptosNotas  implements java.io.Serializable {


     private String codCon;
     private String nomCon;
     private String codCue;
     private char tipCon;
     private String codCueIva;
     private boolean modificado;
     private boolean usertransaction;

    public VenConceptosNotas() {
    }

    public VenConceptosNotas(String codCon, String nomCon, String codCue, char tipCon, String codCueIva, boolean modificado, boolean usertransaction) {
       this.codCon = codCon;
       this.nomCon = nomCon;
       this.codCue = codCue;
       this.tipCon = tipCon;
       this.codCueIva = codCueIva;
       this.modificado = modificado;
       this.usertransaction = usertransaction;
    }
   
    public String getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(String codCon) {
        this.codCon = codCon;
    }
    public String getNomCon() {
        return this.nomCon;
    }
    
    public void setNomCon(String nomCon) {
        this.nomCon = nomCon;
    }
    public String getCodCue() {
        return this.codCue;
    }
    
    public void setCodCue(String codCue) {
        this.codCue = codCue;
    }
    public char getTipCon() {
        return this.tipCon;
    }
    
    public void setTipCon(char tipCon) {
        this.tipCon = tipCon;
    }
    public String getCodCueIva() {
        return this.codCueIva;
    }
    
    public void setCodCueIva(String codCueIva) {
        this.codCueIva = codCueIva;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public boolean isUsertransaction() {
        return this.usertransaction;
    }
    
    public void setUsertransaction(boolean usertransaction) {
        this.usertransaction = usertransaction;
    }




}


