package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0



/**
 * VenDetaCartId generated by hbm2java
 */
public class VenDetaCartId  implements java.io.Serializable {


     private String codAlm;
     private String numPed;
     private String tipPed;
     private String codIns;
     private String codTalla;

    public VenDetaCartId() {
    }

    public VenDetaCartId(String codAlm, String numPed, String tipPed, String codIns, String codTalla) {
       this.codAlm = codAlm;
       this.numPed = numPed;
       this.tipPed = tipPed;
       this.codIns = codIns;
       this.codTalla = codTalla;
    }
   
    public String getCodAlm() {
        return this.codAlm;
    }
    
    public void setCodAlm(String codAlm) {
        this.codAlm = codAlm;
    }
    public String getNumPed() {
        return this.numPed;
    }
    
    public void setNumPed(String numPed) {
        this.numPed = numPed;
    }
    public String getTipPed() {
        return this.tipPed;
    }
    
    public void setTipPed(String tipPed) {
        this.tipPed = tipPed;
    }
    public String getCodIns() {
        return this.codIns;
    }
    
    public void setCodIns(String codIns) {
        this.codIns = codIns;
    }
    public String getCodTalla() {
        return this.codTalla;
    }
    
    public void setCodTalla(String codTalla) {
        this.codTalla = codTalla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VenDetaCartId) ) return false;
		 VenDetaCartId castOther = ( VenDetaCartId ) other; 
         
		 return ( (this.getCodAlm()==castOther.getCodAlm()) || ( this.getCodAlm()!=null && castOther.getCodAlm()!=null && this.getCodAlm().equals(castOther.getCodAlm()) ) )
 && ( (this.getNumPed()==castOther.getNumPed()) || ( this.getNumPed()!=null && castOther.getNumPed()!=null && this.getNumPed().equals(castOther.getNumPed()) ) )
 && ( (this.getTipPed()==castOther.getTipPed()) || ( this.getTipPed()!=null && castOther.getTipPed()!=null && this.getTipPed().equals(castOther.getTipPed()) ) )
 && ( (this.getCodIns()==castOther.getCodIns()) || ( this.getCodIns()!=null && castOther.getCodIns()!=null && this.getCodIns().equals(castOther.getCodIns()) ) )
 && ( (this.getCodTalla()==castOther.getCodTalla()) || ( this.getCodTalla()!=null && castOther.getCodTalla()!=null && this.getCodTalla().equals(castOther.getCodTalla()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlm() == null ? 0 : this.getCodAlm().hashCode() );
         result = 37 * result + ( getNumPed() == null ? 0 : this.getNumPed().hashCode() );
         result = 37 * result + ( getTipPed() == null ? 0 : this.getTipPed().hashCode() );
         result = 37 * result + ( getCodIns() == null ? 0 : this.getCodIns().hashCode() );
         result = 37 * result + ( getCodTalla() == null ? 0 : this.getCodTalla().hashCode() );
         return result;
   }   


}


