package POJOS;
// Generated 25-oct-2014 9:20:16 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * VenDetaFact generated by hbm2java
 */
public class VenDetaFact  implements java.io.Serializable {


     private VenDetaFactId id;
     private BigDecimal valUnitario;
     private BigDecimal valIns;
     private BigDecimal valIva;
     private BigDecimal qtyIns;
     private BigDecimal qtyDev;
     private BigDecimal ivaIns;
     private BigDecimal cosIns;
     private BigDecimal desIns;
     private BigDecimal PList;
     private Character estado;
     private String codIva;
     private String codtalla;
     private String descrip;
     private BigDecimal margenDscto;
     private String lote;
     private String tipped;
     private String codVen;
     private BigDecimal qtyCon;
     private String numped;
     private BigDecimal margenAiu;
     private BigDecimal valAiu;
     private Date fecsys;

    public VenDetaFact() {
    }

	
    public VenDetaFact(VenDetaFactId id, BigDecimal valIva, String codIva, String codtalla, String descrip, BigDecimal margenDscto, String lote, String tipped, String codVen, BigDecimal qtyCon, String numped, BigDecimal margenAiu, BigDecimal valAiu, Date fecsys) {
        this.id = id;
        this.valIva = valIva;
        this.codIva = codIva;
        this.codtalla = codtalla;
        this.descrip = descrip;
        this.margenDscto = margenDscto;
        this.lote = lote;
        this.tipped = tipped;
        this.codVen = codVen;
        this.qtyCon = qtyCon;
        this.numped = numped;
        this.margenAiu = margenAiu;
        this.valAiu = valAiu;
        this.fecsys = fecsys;
    }
    public VenDetaFact(VenDetaFactId id, BigDecimal valUnitario, BigDecimal valIns, BigDecimal valIva, BigDecimal qtyIns, BigDecimal qtyDev, BigDecimal ivaIns, BigDecimal cosIns, BigDecimal desIns, BigDecimal PList, Character estado, String codIva, String codtalla, String descrip, BigDecimal margenDscto, String lote, String tipped, String codVen, BigDecimal qtyCon, String numped, BigDecimal margenAiu, BigDecimal valAiu, Date fecsys) {
       this.id = id;
       this.valUnitario = valUnitario;
       this.valIns = valIns;
       this.valIva = valIva;
       this.qtyIns = qtyIns;
       this.qtyDev = qtyDev;
       this.ivaIns = ivaIns;
       this.cosIns = cosIns;
       this.desIns = desIns;
       this.PList = PList;
       this.estado = estado;
       this.codIva = codIva;
       this.codtalla = codtalla;
       this.descrip = descrip;
       this.margenDscto = margenDscto;
       this.lote = lote;
       this.tipped = tipped;
       this.codVen = codVen;
       this.qtyCon = qtyCon;
       this.numped = numped;
       this.margenAiu = margenAiu;
       this.valAiu = valAiu;
       this.fecsys = fecsys;
    }
   
    public VenDetaFactId getId() {
        return this.id;
    }
    
    public void setId(VenDetaFactId id) {
        this.id = id;
    }
    public BigDecimal getValUnitario() {
        return this.valUnitario;
    }
    
    public void setValUnitario(BigDecimal valUnitario) {
        this.valUnitario = valUnitario;
    }
    public BigDecimal getValIns() {
        return this.valIns;
    }
    
    public void setValIns(BigDecimal valIns) {
        this.valIns = valIns;
    }
    public BigDecimal getValIva() {
        return this.valIva;
    }
    
    public void setValIva(BigDecimal valIva) {
        this.valIva = valIva;
    }
    public BigDecimal getQtyIns() {
        return this.qtyIns;
    }
    
    public void setQtyIns(BigDecimal qtyIns) {
        this.qtyIns = qtyIns;
    }
    public BigDecimal getQtyDev() {
        return this.qtyDev;
    }
    
    public void setQtyDev(BigDecimal qtyDev) {
        this.qtyDev = qtyDev;
    }
    public BigDecimal getIvaIns() {
        return this.ivaIns;
    }
    
    public void setIvaIns(BigDecimal ivaIns) {
        this.ivaIns = ivaIns;
    }
    public BigDecimal getCosIns() {
        return this.cosIns;
    }
    
    public void setCosIns(BigDecimal cosIns) {
        this.cosIns = cosIns;
    }
    public BigDecimal getDesIns() {
        return this.desIns;
    }
    
    public void setDesIns(BigDecimal desIns) {
        this.desIns = desIns;
    }
    public BigDecimal getPList() {
        return this.PList;
    }
    
    public void setPList(BigDecimal PList) {
        this.PList = PList;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getCodIva() {
        return this.codIva;
    }
    
    public void setCodIva(String codIva) {
        this.codIva = codIva;
    }
    public String getCodtalla() {
        return this.codtalla;
    }
    
    public void setCodtalla(String codtalla) {
        this.codtalla = codtalla;
    }
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
    public BigDecimal getMargenDscto() {
        return this.margenDscto;
    }
    
    public void setMargenDscto(BigDecimal margenDscto) {
        this.margenDscto = margenDscto;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public String getTipped() {
        return this.tipped;
    }
    
    public void setTipped(String tipped) {
        this.tipped = tipped;
    }
    public String getCodVen() {
        return this.codVen;
    }
    
    public void setCodVen(String codVen) {
        this.codVen = codVen;
    }
    public BigDecimal getQtyCon() {
        return this.qtyCon;
    }
    
    public void setQtyCon(BigDecimal qtyCon) {
        this.qtyCon = qtyCon;
    }
    public String getNumped() {
        return this.numped;
    }
    
    public void setNumped(String numped) {
        this.numped = numped;
    }
    public BigDecimal getMargenAiu() {
        return this.margenAiu;
    }
    
    public void setMargenAiu(BigDecimal margenAiu) {
        this.margenAiu = margenAiu;
    }
    public BigDecimal getValAiu() {
        return this.valAiu;
    }
    
    public void setValAiu(BigDecimal valAiu) {
        this.valAiu = valAiu;
    }
    public Date getFecsys() {
        return this.fecsys;
    }
    
    public void setFecsys(Date fecsys) {
        this.fecsys = fecsys;
    }




}


