package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * VenDetaCart generated by hbm2java
 */
public class VenDetaCart  implements java.io.Serializable {


     private VenDetaCartId id;
     private BigDecimal qtyPed;
     private BigDecimal qtyRem;
     private String estado;
     private BigDecimal qtyfac;
     private BigDecimal valIva;
     private BigDecimal valDcto;
     private BigDecimal margenDcto;
     private BigDecimal margenIva;
     private BigDecimal valUnitario;

    public VenDetaCart() {
    }

    public VenDetaCart(VenDetaCartId id, BigDecimal qtyPed, BigDecimal qtyRem, String estado, BigDecimal qtyfac, BigDecimal valIva, BigDecimal valDcto, BigDecimal margenDcto, BigDecimal margenIva, BigDecimal valUnitario) {
       this.id = id;
       this.qtyPed = qtyPed;
       this.qtyRem = qtyRem;
       this.estado = estado;
       this.qtyfac = qtyfac;
       this.valIva = valIva;
       this.valDcto = valDcto;
       this.margenDcto = margenDcto;
       this.margenIva = margenIva;
       this.valUnitario = valUnitario;
    }
   
    public VenDetaCartId getId() {
        return this.id;
    }
    
    public void setId(VenDetaCartId id) {
        this.id = id;
    }
    public BigDecimal getQtyPed() {
        return this.qtyPed;
    }
    
    public void setQtyPed(BigDecimal qtyPed) {
        this.qtyPed = qtyPed;
    }
    public BigDecimal getQtyRem() {
        return this.qtyRem;
    }
    
    public void setQtyRem(BigDecimal qtyRem) {
        this.qtyRem = qtyRem;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public BigDecimal getQtyfac() {
        return this.qtyfac;
    }
    
    public void setQtyfac(BigDecimal qtyfac) {
        this.qtyfac = qtyfac;
    }
    public BigDecimal getValIva() {
        return this.valIva;
    }
    
    public void setValIva(BigDecimal valIva) {
        this.valIva = valIva;
    }
    public BigDecimal getValDcto() {
        return this.valDcto;
    }
    
    public void setValDcto(BigDecimal valDcto) {
        this.valDcto = valDcto;
    }
    public BigDecimal getMargenDcto() {
        return this.margenDcto;
    }
    
    public void setMargenDcto(BigDecimal margenDcto) {
        this.margenDcto = margenDcto;
    }
    public BigDecimal getMargenIva() {
        return this.margenIva;
    }
    
    public void setMargenIva(BigDecimal margenIva) {
        this.margenIva = margenIva;
    }
    public BigDecimal getValUnitario() {
        return this.valUnitario;
    }
    
    public void setValUnitario(BigDecimal valUnitario) {
        this.valUnitario = valUnitario;
    }




}


