package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * VenFpsxLp generated by hbm2java
 */
public class VenFpsxLp  implements java.io.Serializable {


     private VenFpsxLpId id;

    public VenFpsxLp() {
    }

    public VenFpsxLp(VenFpsxLpId id) {
       this.id = id;
    }
   
    public VenFpsxLpId getId() {
        return this.id;
    }
    
    public void setId(VenFpsxLpId id) {
        this.id = id;
    }




}


