package POJOS;
// Generated 21-oct-2014 16:02:55 by Hibernate Tools 3.6.0



/**
 * VenFpsxLpId generated by hbm2java
 */
public class VenFpsxLpId  implements java.io.Serializable {


     private String codList;
     private String codFor;

    public VenFpsxLpId() {
    }

    public VenFpsxLpId(String codList, String codFor) {
       this.codList = codList;
       this.codFor = codFor;
    }
   
    public String getCodList() {
        return this.codList;
    }
    
    public void setCodList(String codList) {
        this.codList = codList;
    }
    public String getCodFor() {
        return this.codFor;
    }
    
    public void setCodFor(String codFor) {
        this.codFor = codFor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VenFpsxLpId) ) return false;
		 VenFpsxLpId castOther = ( VenFpsxLpId ) other; 
         
		 return ( (this.getCodList()==castOther.getCodList()) || ( this.getCodList()!=null && castOther.getCodList()!=null && this.getCodList().equals(castOther.getCodList()) ) )
 && ( (this.getCodFor()==castOther.getCodFor()) || ( this.getCodFor()!=null && castOther.getCodFor()!=null && this.getCodFor().equals(castOther.getCodFor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodList() == null ? 0 : this.getCodList().hashCode() );
         result = 37 * result + ( getCodFor() == null ? 0 : this.getCodFor().hashCode() );
         return result;
   }   


}


