package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * VenIvas generated by hbm2java
 */
public class VenIvas  implements java.io.Serializable {


     private BigDecimal margenIva;
     private String nomIva;
     private String codIva;
     private boolean modificado;

    public VenIvas() {
    }

    public VenIvas(BigDecimal margenIva, String nomIva, String codIva, boolean modificado) {
       this.margenIva = margenIva;
       this.nomIva = nomIva;
       this.codIva = codIva;
       this.modificado = modificado;
    }
   
    public BigDecimal getMargenIva() {
        return this.margenIva;
    }
    
    public void setMargenIva(BigDecimal margenIva) {
        this.margenIva = margenIva;
    }
    public String getNomIva() {
        return this.nomIva;
    }
    
    public void setNomIva(String nomIva) {
        this.nomIva = nomIva;
    }
    public String getCodIva() {
        return this.codIva;
    }
    
    public void setCodIva(String codIva) {
        this.codIva = codIva;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }




}


