package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * VenListaPreciosJoin generated by hbm2java
 */
public class VenListaPreciosJoin  implements java.io.Serializable {


     private VenListaPreciosJoinId id;
     private BigDecimal margenInc;

    public VenListaPreciosJoin() {
    }

    public VenListaPreciosJoin(VenListaPreciosJoinId id, BigDecimal margenInc) {
       this.id = id;
       this.margenInc = margenInc;
    }
   
    public VenListaPreciosJoinId getId() {
        return this.id;
    }
    
    public void setId(VenListaPreciosJoinId id) {
        this.id = id;
    }
    public BigDecimal getMargenInc() {
        return this.margenInc;
    }
    
    public void setMargenInc(BigDecimal margenInc) {
        this.margenInc = margenInc;
    }




}


