package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * VenMaeCartId generated by hbm2java
 */
public class VenMaeCartId  implements java.io.Serializable {


     private String codAlm;
     private String numPed;
     private String tipPed;

    public VenMaeCartId() {
    }

    public VenMaeCartId(String codAlm, String numPed, String tipPed) {
       this.codAlm = codAlm;
       this.numPed = numPed;
       this.tipPed = tipPed;
    }
   
    public String getCodAlm() {
        return this.codAlm;
    }
    
    public void setCodAlm(String codAlm) {
        this.codAlm = codAlm;
    }
    public String getNumPed() {
        return this.numPed;
    }
    
    public void setNumPed(String numPed) {
        this.numPed = numPed;
    }
    public String getTipPed() {
        return this.tipPed;
    }
    
    public void setTipPed(String tipPed) {
        this.tipPed = tipPed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VenMaeCartId) ) return false;
		 VenMaeCartId castOther = ( VenMaeCartId ) other; 
         
		 return ( (this.getCodAlm()==castOther.getCodAlm()) || ( this.getCodAlm()!=null && castOther.getCodAlm()!=null && this.getCodAlm().equals(castOther.getCodAlm()) ) )
 && ( (this.getNumPed()==castOther.getNumPed()) || ( this.getNumPed()!=null && castOther.getNumPed()!=null && this.getNumPed().equals(castOther.getNumPed()) ) )
 && ( (this.getTipPed()==castOther.getTipPed()) || ( this.getTipPed()!=null && castOther.getTipPed()!=null && this.getTipPed().equals(castOther.getTipPed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlm() == null ? 0 : this.getCodAlm().hashCode() );
         result = 37 * result + ( getNumPed() == null ? 0 : this.getNumPed().hashCode() );
         result = 37 * result + ( getTipPed() == null ? 0 : this.getTipPed().hashCode() );
         return result;
   }   


}


