package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * VenMaeCotizaOpc generated by hbm2java
 */
public class VenMaeCotizaOpc  implements java.io.Serializable {


     private VenMaeCotizaOpcId id;
     private String refopc;
     private String forpag;
     private BigDecimal subTotal;
     private BigDecimal valDesc;
     private BigDecimal valIva;
     private BigDecimal valCot;

    public VenMaeCotizaOpc() {
    }

    public VenMaeCotizaOpc(VenMaeCotizaOpcId id, String refopc, String forpag, BigDecimal subTotal, BigDecimal valDesc, BigDecimal valIva, BigDecimal valCot) {
       this.id = id;
       this.refopc = refopc;
       this.forpag = forpag;
       this.subTotal = subTotal;
       this.valDesc = valDesc;
       this.valIva = valIva;
       this.valCot = valCot;
    }
   
    public VenMaeCotizaOpcId getId() {
        return this.id;
    }
    
    public void setId(VenMaeCotizaOpcId id) {
        this.id = id;
    }
    public String getRefopc() {
        return this.refopc;
    }
    
    public void setRefopc(String refopc) {
        this.refopc = refopc;
    }
    public String getForpag() {
        return this.forpag;
    }
    
    public void setForpag(String forpag) {
        this.forpag = forpag;
    }
    public BigDecimal getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }
    public BigDecimal getValDesc() {
        return this.valDesc;
    }
    
    public void setValDesc(BigDecimal valDesc) {
        this.valDesc = valDesc;
    }
    public BigDecimal getValIva() {
        return this.valIva;
    }
    
    public void setValIva(BigDecimal valIva) {
        this.valIva = valIva;
    }
    public BigDecimal getValCot() {
        return this.valCot;
    }
    
    public void setValCot(BigDecimal valCot) {
        this.valCot = valCot;
    }




}


