package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * VenMaeCart generated by hbm2java
 */
public class VenMaeCart  implements java.io.Serializable {


     private VenMaeCartId id;
     private Date fecPed;
     private Date fecSys;
     private String codUsu;
     private String pc;
     private String estado;
     private String codter;
     private String codVen;
     private String codList;
     private String codSuc;

    public VenMaeCart() {
    }

    public VenMaeCart(VenMaeCartId id, Date fecPed, Date fecSys, String codUsu, String pc, String estado, String codter, String codVen, String codList, String codSuc) {
       this.id = id;
       this.fecPed = fecPed;
       this.fecSys = fecSys;
       this.codUsu = codUsu;
       this.pc = pc;
       this.estado = estado;
       this.codter = codter;
       this.codVen = codVen;
       this.codList = codList;
       this.codSuc = codSuc;
    }
   
    public VenMaeCartId getId() {
        return this.id;
    }
    
    public void setId(VenMaeCartId id) {
        this.id = id;
    }
    public Date getFecPed() {
        return this.fecPed;
    }
    
    public void setFecPed(Date fecPed) {
        this.fecPed = fecPed;
    }
    public Date getFecSys() {
        return this.fecSys;
    }
    
    public void setFecSys(Date fecSys) {
        this.fecSys = fecSys;
    }
    public String getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(String codUsu) {
        this.codUsu = codUsu;
    }
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodter() {
        return this.codter;
    }
    
    public void setCodter(String codter) {
        this.codter = codter;
    }
    public String getCodVen() {
        return this.codVen;
    }
    
    public void setCodVen(String codVen) {
        this.codVen = codVen;
    }
    public String getCodList() {
        return this.codList;
    }
    
    public void setCodList(String codList) {
        this.codList = codList;
    }
    public String getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(String codSuc) {
        this.codSuc = codSuc;
    }




}


