package POJOS;
// Generated 23-oct-2014 8:25:39 by Hibernate Tools 3.6.0



/**
 * VenRetsXCliente generated by hbm2java
 */
public class VenRetsXCliente  implements java.io.Serializable {


     private VenRetsXClienteId id;

    public VenRetsXCliente() {
    }

    public VenRetsXCliente(VenRetsXClienteId id) {
       this.id = id;
    }
   
    public VenRetsXClienteId getId() {
        return this.id;
    }
    
    public void setId(VenRetsXClienteId id) {
        this.id = id;
    }




}


