package POJOS;
// Generated 19-sep-2014 10:35:39 by Hibernate Tools 3.6.0



/**
 * VenVendxAlm generated by hbm2java
 */
public class VenVendxAlm  implements java.io.Serializable {


     private VenVendxAlmId id;

    public VenVendxAlm() {
    }

    public VenVendxAlm(VenVendxAlmId id) {
       this.id = id;
    }
   
    public VenVendxAlmId getId() {
        return this.id;
    }
    
    public void setId(VenVendxAlmId id) {
        this.id = id;
    }




}


